/*! -- File: test.js ( Input 0 ) -- */
var DKI;DKI||(DKI={});
DKI.TestQuestion=function(){var a=$(document.body).data("singlepage")?!0:!1;480>=screen.availWidth||$(document.body).width();var b={submit:function(k,e){var c=!1;"undefined"!=typeof dataStorage&&dataStorage.currentModule.forceTestEnd&&(c=dataStorage.currentModule.forceTestEnd);if(this.submitted){if(!a&&!this.isPracticeQuestion&&settings.enableTimerQuestions&&c)return $(document).trigger(DKI.Events.TestQuestion.forceEnd),!1;$(document).trigger(DKI.Events.TestQuestion.nextClicked);return null}this.submitted=
!0;this.getOptions();k&&(k.preventDefault(),k.stopPropagation());if(b.overMaxOptions.call(this))return alert(this.strings.tstchoicesLabel1+" "+this.maxSelections+" "+this.strings.tstchoicesLabel2),this.submitted=!1;if(!this.hasSelection.call(this)&&(!settings.enableTimerQuestions||settings.enableTimerQuestions&&!c)&&!confirm(this.strings.confirmQuestionNoSelection))return this.submitted=!1;this.submitButton.unbind();e=e?e:0;this.numAttempts++;if(a||this.isPracticeQuestion)e=b.scorePreview.call(this,
e),this.setScore(e);else{e=b.scoreExport.call(this,e,c);k=!1;"undefined"!=typeof dataStorage&&dataStorage.currentModule.forceEndPre&&(k=dataStorage.currentModule.forceEndPre);if(settings.enableTimerQuestions&&c||k)return $(document).trigger(DKI.Events.TestQuestion.forceEnd),!1;$(document).trigger(DKI.Events.TestQuestion.exportSubmitted)}100==e&&($(this.pageContainer).trigger(DKI.Events.TestQuestion.correct),this.numAttempts<this.question.attempts&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptSubmitted),
this.numAttempts=this.question.attempts);this.numAttempts==this.question.attempts?($(this.pageContainer).trigger(DKI.Events.TestQuestion.submitted),0>=e?$(this.pageContainer).trigger(DKI.Events.TestQuestion.incorrect):100>e&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.partiallyCorrect)):($(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptSubmitted),0>=e?$(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptIncorrect):100>e&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptPartiallyCorrect));
return!1},overMaxOptions:function(){var a=!1,e=0;if(2==this.questionType||3==this.questionType){for(var c=this.getOptions(),b=0;b<c.length;b++)1==c[b].value().checked&&e++;e>this.maxSelections&&(a=!0)}return a},atMaxOptions:function(){var a=!1,e=0;if(2==this.questionType||3==this.questionType){for(var c=this.getOptions(),b=0;b<c.length;b++){var d=$("input",c[b].wrapper);d.attr("attr-checked")&&"true"==d.attr("attr-checked").toString()&&e++}e==this.maxSelections&&(a=!0)}return a},showDefaultSubmit:function(){var a=
this,e='\x3cdiv class \x3d "button-wrapper '+this.getSubmitButtonWrapperClass()+'"\x3e\x3cbutton role\x3d"button" tabindex\x3d"1" class\x3d"btn btn-primary btn-block dki-submit-button"\x3e'+DKI.strings.runtime.buttonLabelSubmit+"\x3c/button\x3e\x3c/div\x3e";"popup"==player.submitButtonPosition||6==this.questionType?(6==this.questionType&&(e='\x3cdiv class \x3d "button-wrapper dragdrop"\x3e\x3cbutton role\x3d"button" tabindex\x3d"1" class\x3d"btn btn-primary btn-block dki-submit-button"\x3e'+DKI.strings.runtime.buttonLabelSubmit+
"\x3c/button\x3e\x3c/div\x3e"),setTimeout(function(){a.question.page_id==player.contentPage.current.page.page.id&&contentApi.showPopup({html:e,effect:"fade",style:"default",autoFocus:!1,popupType:{mod:"botRight dki-submit-button",modal:!1,type:"notification"},id:"dki-submit-"+a.question.id,tabContent:!1,role:"",afterShow:function(){$(a.pageContainer).css("padding-bottom","");a.settings.responsive&&!theme.preventPaddingForSubmit&&a.getContentHeight()+$("#action_popup_dki-submit-"+a.question.id).height()>
a.pageContainer.scrollHeight&&$(a.pageContainer).css("padding-bottom",$("#action_popup_dki-submit-"+a.question.id).height());a.submitButton=$("#action_popup_dki-submit-"+a.question.id+" .dki-submit-button");a.submitButton.on(settings.clickEvent,function(){contentApi.submitQuestion()});a.positionSubmitButtonImmediate();$(document).trigger(DKI.Events.TestQuestion.submitButtonShown,a.submitButton)}})},50)):(a.submitButton=$(e),"belowPage"==player.submitButtonPosition&&(submitPosition=$("\x3cdiv/\x3e",
{"class":"submitButtonBelowPage"}),$(".dki-authoring-row",this.pageContainer).last().after(a.submitButton)),"belowQuestionOptions"==player.submitButtonPosition&&6!=this.questionType&&(submitPosition=$("\x3cdiv/\x3e",{"class":"submitButtonBelowOptions"}),$(".dki-authoring-element[data-isquestionoption\x3d'true']",this.pageContainer).last().after(a.submitButton)),a.submitButton=a.submitButton.find("Button"),$(".try-again-wrapper").remove(),a.submitButton.on(settings.clickEvent,function(){contentApi.submitQuestion()}))},
scorePreview:function(b){var e=this.getOptions(),c=this.getCorrectCount(),d=0,g=0,f;b="undefined"===typeof b?0:b;var m=!1;if("pre"==this.prePost&&this.behaviour.reviewPreAnswers||"post"==this.prePost&&this.behaviour.reviewPostAnswers)m=!0;if(13==this.questionType)b=this.calculate(m);else if(11==this.questionType||12==this.questionType)b=this.calculate(),this.showInlineFeedback();else{for(var l=0;l<e.length;l++)f=e[l].score(),1===f?d++:-1===f&&g++,e[l].value(),e[l].showCorrect(m);b=this.calculate(c,
d,g,b)}!this.isPracticeQuestion&&a&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.questionInReview);l=$(".dki-questionBody-element .dki-element-content",this.pageContainer);c={type:this.questionType,body:l.text().trim(),latency:(new Date).getTime()-this.startTime,options:[],data:this.getData()};for(l=0;l<e.length;l++)c.options[l]=e[l].value();"undefined"==typeof dataStorage||this.inReview||$(this.player.dataStorage).trigger(DKI.DataStorage.events.questionScored,{question:dataStorage.currentPage.question,
questionObject:c,score:b,test:this});$(".dki-authoring-element",this.pageContainer).has(".correct, .incorrect, .multiChoiceCorrect").css("zIndex",1E5);return b},scoreExport:function(a,e){for(var b=this.getOptions(),c={type:this.questionType,body:this.getBodyText(),latency:(new Date).getTime()-this.startTime,options:[],data:this.getData()},d=0;d<b.length;d++)c.options[d]=b[d].value(),this.behaviour.IncludeQuestionNumbering&&(c.options[d].text=$(".optionNumber",b[d].wrapper).text()+c.options[d].text);
return a=this.player.dataStorage.submitCurrentQuestion(c,a,e,this)},showCorrectFeedback:function(){return b.doShowFeedback.call(this,"correct")},showIncorrectFeedback:function(){return b.doShowFeedback.call(this,"incorrect")},showIncorrectAttemptFeedback:function(){return b.doShowFeedback.call(this,"incorrectAttempt")},showPartialFeedback:function(){return b.doShowFeedback.call(this,"partial")},showPartialAttemptFeedback:function(){return b.doShowFeedback.call(this,"partialAttempt")},doShowFeedback:function(c){var e=
this.getFeedbackConfig(),d=e[3==this.question.type?"incorrect":c],n=e.popup;"true"==n.use_course_default.toString()&&(n=contentApi.getDefaultFeedbackPopup());var g=this,f="",f=d.useDefault?f+contentApi.getDefaultFeedbackText(c):f+d.text,e=this.getOptionFeedback();""!=e&&(""==f?1==(e.match(/&bull;/g)||[]).length&&(e=e.replace(/&bull;/g,"")):f+="\x3chr/\x3e",f+=e);var m=function(){8!=g.question.type&&(13!=g.question.type&&g.showInlineFeedback(),f&&contentApi.showPopup({ariaLabel:DKI.strings.doc["Question feedback header"],
html:f,title:"",effect:"fade",style:function(){var a="success";if("incorrect"==c||"incorrectAttempt"==c)a="danger";else if("partial"==c||"partialAttempt"==c)a="warning";return a}(),autoFocus:!0,popupType:{mod:n.mod,modal:n.modal,type:n.type},id:"question_"+g.question.id+"_feedback",addClass:"DKI-questionFeedback",returnFocus:$("button.dki-try-again")[0]?$("button.dki-try-again")[0]:document.activeElement}))},l=function(){for(var a=this.page.actions,b=function(a){if("api"==a.type){if(a=a.parameters.method,
"hideForward"==a||"hideBack"==a||"hideBoth"==a||"showForward"==a||"showBack"==a||"showBoth"==a)return!0}else if("setVariable"==a.type||"sendXAPIStatement"==a.type)return!0;return!1},e=0;e<a.length;e++){if(a[e].trigger==DKI.Events.TestQuestion.submitted&&!b(a[e]))return!0;if(a[e].trigger==DKI.Events.TestQuestion.correct&&!b(a[e])){if("correct"==c)return!0}else if(a[e].trigger==DKI.Events.TestQuestion.incorrect&&!b(a[e])){if("incorrect"==c)return!0}else if(a[e].trigger!=DKI.Events.TestQuestion.partiallyCorrect||
b(a[e])){if(a[e].trigger==DKI.Events.TestQuestion.attemptSubmitted&&!b(a[e]))return!0;if(a[e].trigger==DKI.Events.TestQuestion.attemptIncorrect&&!b(a[e])){if("incorrectAttempt"==c)return!0}else if(a[e].trigger==DKI.Events.TestQuestion.attemptPartiallyCorrect&&!b(a[e])&&"partialAttempt"==c)return!0}else if("partial"==c)return!0}return!1},p=function(){var a='\x3cdiv class\x3d"try-again-wrapper '+g.getSubmitButtonWrapperClass()+'"\x3e\x3cspan class\x3d"remainingAttempts" tabindex\x3d"1"\x3e'+DKI.strings.runtime.txtRemainingAttempts+
" "+(g.question.attempts-g.numAttempts)+'\x3c/span\x3e\x3cbutton class\x3d"btn btn-primary dki-try-again" tabindex\x3d"1" onclick\x3d"contentApi.tryAgain();" data-dismiss\x3d"alert"\x3e'+DKI.strings.runtime.testTryAgain+"\x3c/button\x3e\x3cdiv\x3e";!g.inReview&&g.isPracticeQuestion&&g.question.show_try_again&&g.numAttempts<g.question.attempts&&("incorrectAttempt"==c||"partialAttempt"==c)?8!==g.questionType&&("popup"==player.submitButtonPosition||6==g.questionType?contentApi.showPopup({html:a,effect:"fade",
style:"default",autoFocus:!0,popupType:{mod:"botRight dki-try-again",modal:!1,type:"notification"},id:"dki-try-again-"+g.question.id,returnFocus:document.activeElement,tabContent:!1,role:"",afterShow:function(){g.tryAgainButton=$("#content_dki-try-again-"+g.question.id+" .dki-try-again");g.positionSubmitButton(g);$("#content_dki-try-again-"+g.question.id+" .remainingAttempts").focus()}}):("belowPage"==player.submitButtonPosition&&$(".dki-authoring-row",g.pageContainer).last().after(a),"belowQuestionOptions"==
player.submitButtonPosition&&6!=g.questionType&&$(".dki-authoring-element[data-isquestionoption\x3d'true']",g.pageContainer).last().after(a),$(".dki-submit-button").remove(),$("#content_dki-try-again-"+g.question.id+" .remainingAttempts").focus())):(g.submitButton.text(g.strings.buttonLabelNext),g.submitButton.off(),g.submitButton.on(g.player.settings.clickEvent,$.proxy(function(a){g.submitButton.unbind(a);g.submitButton.hide();a.preventDefault();a.stopPropagation();g.page.isStandalonePage?$.fancybox.close():
$(document).trigger(DKI.Events.TestQuestion.nextClicked)},g)),(7==g.questionType||8==g.questionType&&!g.inReview)&&g.submitButton.trigger(g.player.settings.clickEvent))},q=function(){if(b.showFeedback.call(g)){if(""!=f||g.hasInlineFeedback())setTimeout(p,100),g.inReview?setTimeout(function(){m()},500):m();else{if(8==g.question.type)return setTimeout(p,100),!1;if(g.inReview||g.isPracticeQuestion||a||dataStorage.currentModule.forceTestEnd||dataStorage.currentModule.forceEndPre||l.call(g))setTimeout(p,
100);else return setTimeout(function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},0),!1}return!0}if(8==g.question.type)return setTimeout(p,100),!1;g.inReview||g.isPracticeQuestion||a||dataStorage.currentModule.forceTestEnd||dataStorage.currentModule.forceEndPre||l.call(g)?setTimeout(p,100):setTimeout(function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},0)};if(this.page.started)q();else $(document).one(DKI.ContentPage.events.started,function(){q()});return!1},showFeedback:function(){return!this.behaviour||
this.preview?!0:this.inReview||!this.behaviour.displayQuestionFeedback&&!this.isPracticeQuestion?this.inReview?"pre"==this.prePost&&this.behaviour.reviewPreFeedback?!0:"post"==this.prePost&&this.behaviour.reviewPostFeedback?!0:!1:!1:!0},showAnswers:function(a){return this.isPracticeQuestion||this.behaviour&&!this.preview?this.inReview&&!a||this.inReview&&a&&("pre"==this.prePost&&this.behaviour.reviewPreAnswers||"post"==this.prePost&&this.behaviour.reviewPostAnswers)?!0:!1:!0}},d={setPrePost:function(a){this.prePost=
a?a:"post"},setScore:function(a,e,c){a=void 0!==a&&null!==a?parseFloat(a,10):0;var d=!0;this.isPracticeQuestion&&(d=this.numAttempts==this.question.attempts);7!==this.questionType&&(a=0>=a?d?b.showIncorrectFeedback.call(this):b.showIncorrectAttemptFeedback.call(this):100===a?b.showCorrectFeedback.call(this):d?b.showPartialFeedback.call(this):b.showPartialAttemptFeedback.call(this))&&$(document).trigger(DKI.Events.TestQuestion.feedbackShown);a=this.getOptions();for(d=0;d<a.length;d++)a[d].enabled(!1);
this.inReview&&($(".questionScoreLabel").text(player.strings.txtScore+(" "!=player.strings.txtScore.slice(-1)?" ":"")),$(".questionScore").text(e+" / "+c+" "+this.strings.txtPoints),$(document.body).hasClass("phone")?this.scoreDisplay.show():this.scoreDisplay.fadeIn(200))},getSubmitButtonWrapperClass:function(){return 6==this.questionType?"button-position-popup":"button-position-"+player.submitButtonPosition},setOptions:function(a,e){for(var c=this.getOptions(),b=0;b<c.length;b++)c[b].value(a[b]),
c[b].enabled(!1),c[b].correctResponse(e[b]);2==this.questionType&&$(".dki-multiChoiceOption-element .multiChoiceContentWrapper").css("visibility","")},showReview:function(a,c,d,n){this.inReview=!0;this.numAttempts=this.question.attempts;this.setPrePost(a);this.setOptions(c,d);var g=7==this.questionType?[n.score]:[];this.onShowReview($.proxy(function(){b.scorePreview.apply(this,g);this.setScore(n.score,n.points,n.weight);$(this.pageContainer).trigger(DKI.Events.TestQuestion.questionInReview);this.question.disable_submit||
this.settings.responsive||7!=this.questionType&&($(document.body).hasClass("phone")?this.submitButton.show():this.submitButton.fadeIn(500))},this))},showCorrectAnswers:function(){for(var a=this.getOptions(),c=0;c<a.length;c++)a[c].showCorrect(!0)},tryAgain:function(){this.reset({doNotResetAttempts:!0});this.tryAgainButton=null;$(document).trigger(DKI.Events.TestQuestion.retry);this.start()},submitQuestion:function(a){b.submit.call(this,null,a)},start:function(){this.startTime=(new Date).getTime();
var a=this;this.page.resize();this.page.start();this.startOptions();!this.question.disable_submit&&7!=this.question.type&&(10!==this.question.type&&8!=this.question.type||this.inReview)&&b.showDefaultSubmit.call(this);6==this.questionType&&($(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).draggable({revert:function(a){var c=settings.responsive;$(this).hasClass("dki-authoring-element-element")&&
(c=!settings.elementTypeConfig[$(this).parent().closest(".dki-authoring-element, .dki-authoring-element-element").data("elementtype")].hasStackableElementElements);$(this).data("uiDraggable").originalPosition={top:c?0:$(this).data("y"),left:c?0:$(this).data("x")};if(a)$(this).addClass("dropped"),$(this).trigger(DKI.ContentPage.events.elementDragDropped);else return $(this).removeClass("dropped"),$(this).css("z-index",$(this).data("elementno")),$(this).data("reverted",!0),$(this).trigger(DKI.ContentPage.events.elementDragReverted),
!0},drag:function(a,c){$(this).hasClass("dki-authoring-element-element")?(a=$(this).parent().closest(".dki-authoring-element, .dki-authoring-element-element").data("scaleRatio"),DKI.utility.dragFix(c,a)):DKI.utility.dragFix(c)},start:function(a,c){1!=$(this).data("reverted")&&"undefined"!=typeof $(this).data("reverted")||$(this).data("origPosition",$(this).position());$(this).hasClass("dki-authoring-element-element")||$(this).parent().css("position","static");$(this).data("reverted",!1);a=$(this).data("title");
""==a&&(a=$(this).text());$(this).data("dropData",{id:$(this).data("dragdropid"),elementId:$(this).data("id"),title:a,target:{id:null,title:"No Target"},x:$(this).data("x"),y:$(this).data("y"),scale:1});$(this).data("initialPageYOffset",document.documentElement.scrollTop);$(this).trigger(DKI.ContentPage.events.elementDragStarted);$(document).trigger(DKI.Events.TestQuestion.dragStarted)},stop:function(a,c){$(this).data("reverted")?($(this).css("z-index",$(this).data("elementno")),a=settings.responsive,
$(this).hasClass("dki-authoring-element-element")&&(a=!settings.elementTypeConfig[$(this).parent().closest(".dki-authoring-element, .dki-authoring-element-element").data("elementtype")].hasStackableElementElements),a&&$(this).css({top:"",left:""}),$(this).data("uiDraggable").originalPosition={top:$(this).data("y"),left:$(this).data("x")}):$(this).css("z-index",1E5);$(this).trigger(DKI.ContentPage.events.elementDragStopped);$(document).trigger(DKI.Events.TestQuestion.dragStopped)},stack:".dkiContentFrame.current .dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue], .fancybox-content .dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue],.dkiContentFrame.current .dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue], .fancybox-content .dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",
scroll:settings.responsive,zIndex:1E5,disabled:!1}),$(".dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).droppable({accept:".dkiContentFrame.current .dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue], .fancybox-content .dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue],.dkiContentFrame.current .dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue], .fancybox-content .dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",
tolerance:"pointer",out:function(a,c){$(this).trigger(DKI.ContentPage.events.elementDropOut)},over:function(a,c){$(this).trigger(DKI.ContentPage.events.elementDropOver)},drop:function(c,b){c=b.draggable.data("title");""==c&&(c=b.draggable.text());var d=$(this).data("title");""==d&&(d=$(this).text());var g=function(){},f=b.draggable.position(),m=settings.scale;if($(this).hasClass("dki-authoring-element-element"))var l=$(this).parent().closest(".dki-authoring-element, .dki-authoring-element-element").data("scaleRatio")||
1,m=m*l;!settings.responsive&&b.helper.closest(".fancybox-container").length&&(m*=settings.claroLightboxScaling);a.question.parameters.snapToCenter&&"true"==a.question.parameters.snapToCenter.toString()&&a.snapDraggableToCenter(b.draggable,$(this),g);b.draggable.data("dropData",{id:b.draggable.data("dragdropid"),elementId:b.draggable.data("id"),title:c,target:{id:$(this).data("dragdropid"),title:d},x:f.left,y:f.top,scale:m});$(this).trigger(DKI.ContentPage.events.elementDropDropped)},disabled:!1}));
8==this.questionType&&DKI.TestQuestion.captureQuestion.init(this);9==this.questionType&&DKI.TestQuestion.imageMapQuestion.init(this);10==this.questionType&&DKI.TestQuestion.scenarioQuestion.init(this);11==this.questionType&&DKI.TestQuestion.matchingQuestion.init(this);12==this.questionType&&DKI.TestQuestion.sequencingQuestion.init(this);13==this.questionType&&DKI.TestQuestion.MultipleChoiceQuestionWidget.init(this);14==this.questionType&&DKI.TestQuestion.FillInTheBlanksQuestionWidget.init(this)},
snapDraggableToCenter:function(a,c,b){DKI.isDefined(b)||(b=function(){});if(c.hasClass("dki-authoring-element-element")){var d=0,g=0;c.hasClass("dki-authoring-element-element")&&(responsive=!settings.elementTypeConfig[c.parent().closest(".dki-authoring-element, .dki-authoring-element-element").data("elementtype")].hasStackableElementElements);if(c.hasClass("dki-authoring-element-element"))if(g=d=0,responsive?(d=a.height()/2+a.parent().offset().top+parseInt(a.css("margin-top")),g=a.width()/2+a.parent().offset().left+
parseInt(a.css("margin-left"))):(d=a.height()/2,g=a.width()/2),c.closest(".dki-authoring-element").hasClass("stackable_element"))var f={top:c.data("y"),left:c.data("x")},d=f.top+c.height()/2-d,f=f.left+c.width()/2-g;else f=c.offset(),f.top/=scale,f.left/=scale,c=c.find("\x3e.dki-authoring-content-wrapper").first(),d=f.top+parseInt(c.css("padding-top"))+(c.height()-parseInt(c.css("padding-bottom")))/2-d,f=f.left+parseInt(c.css("padding-left"))+(c.width()-parseInt(c.css("padding-left")))/2-g;else if(responsive){var f=
c.offset(),m=c.closest(".dki-authoring-element").data("scaleRatio")||1;f.top/=scale;f.left/=scale;d=f.top+c.height()*m/2-d;f=f.left+c.width()*m/2-g}else f=c.offset(),f.top/=scale,f.left/=scale,c=c.find("\x3e.dki-authoring-content-wrapper").first(),d=f.top+parseInt(c.css("padding-top"))+(c.height()-parseInt(c.css("padding-bottom")))/2-d,f=f.left+parseInt(c.css("padding-left"))+(c.width()-parseInt(c.css("padding-left")))/2-g}else settings.responsive?(f=c.offset(),g=a.find("\x3e.dki-authoring-content-wrapper").first(),
c=c.find("\x3e.dki-authoring-content-wrapper").first(),d=f.top+parseInt(c.css("padding-top"))+(c.height()-parseInt(c.css("padding-bottom")))/2-g.outerHeight()/2-(a.data("origPosition").top+a.parent().offset().top+parseInt(a.css("margin-top"))),f=f.left+parseInt(c.css("padding-left"))+(c.width()-parseInt(c.css("padding-left")))/2-g.outerWidth()/2-(a.parent().offset().left+parseInt(a.css("margin-left")))):(f=c.position(),d=f.top+c.height()/2-a.height()/2,f=f.left+c.width()/2-a.width()/2);position={top:d,
left:f};a.animate({top:d+"px",left:f+"px"},125,b)},reset:function(a){a=DKI.applyIf(a,{doNotResetAttempts:!1,timeout:0});var c=this;contentApi.destroyPopup("question_"+this.question.id+"_feedback");contentApi.destroyPopup("dki-submit-"+this.question.id);contentApi.destroyPopup("dki-try-again-"+this.question.id);c.settings.responsive&&$(c.pageContainer).css("padding-bottom","");c.submitButton.hide();c.submitButton.unbind();var b=function(){c.submitted=!1;a.doNotResetAttempts||(c.numAttempts=0);a.timeout=
0;c.page.reset(a);c.resetOptions();6==c.questionType&&($(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",c.pageContainer).draggable("option","disabled",!0),$(".dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",c.pageContainer).droppable("option","disabled",
!0))};0<a.timeout?setTimeout(b,a.timeout):b()},startOptions:function(){for(var a=this.getOptions(),c=0;c<a.length;c++)a[c].start()},resetOptions:function(){for(var a=this.getOptions(),c=0;c<a.length;c++)a[c].reset();2==this.question.type&&this.randomizeOptions()},onWindowResize:function(){var a=this;this.page.onWindowResize();$(this.page.pageContainer).hasClass("current")&&(a.positionSubmitButton(a),a.settings.responsive&&6==this.questionType&&$(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",
this.pageContainer).filter(".dropped").each(function(){var c=$("[data-dragdropid\x3d"+$(this).data("dropData").target.id+"]",a.pageContainer);a.snapDraggableToCenter($(this),c)}))},canShowFeedback:function(){return b.showFeedback.call(this)},canShowCorrectAnswers:function(){return b.showAnswers.call(this,!0)},canShowGivenAnswers:function(){return b.showAnswers.call(this)},getFeedbackConfig:function(a){return this.question.parameters.feedback},getBodyText:function(){return $(".dki-questionBody-element .dki-element-content",
this.pageContainer).text()},positionSubmitButtonImmediate:function(){if(this.submitButton.is(":visible")){var a=this.submitButton.closest(".notification");this.page.isStandalonePage||a.css("z-index",98E3);if(settings.responsive){var c=$("#contentFrame").offset(),b;b=$("html").attr("dir")&&"rtl"==$("html").attr("dir").toLowerCase()?0:$("#contentFrame").width()-a.outerWidth()-settings.course.parameters.submitButtonOffset.right;settings.design.is_rtl||(b+=c.left);var d=parseInt($(".bgRepeater").css("padding-bottom").split("px")[0],
10),d=d+settings.course.parameters.submitButtonOffset.bottom;a.css({left:0>b?0:b,bottom:d,right:"auto"});$("#skipToNavigationWrapper").length&&$("#skipToNavigationWrapper").before(a.detach());this.tryAgainButton&&(a=this.tryAgainButton.closest(".notification"),b=$("html").attr("dir")&&"rtl"==$("html").attr("dir").toLowerCase()?0:$("#contentFrame").width()-a.outerWidth()-settings.course.parameters.submitButtonOffset.right,settings.design.is_rtl||(b+=c.left),a.css({left:0>b?0:b,bottom:d,right:"auto"}),
$("#skipToNavigationWrapper").length&&$("#skipToNavigationWrapper").before(a.detach()))}else c=$(".bgRepeater").offset(),c.top/=settings.scale,c.left/=settings.scale,b=c.left+$(".bgRepeater").width()-settings.course.parameters.submitButtonOffset.right,d=c.top+$(".bgRepeater").height()-settings.course.parameters.submitButtonOffset.bottom,b=Math.min(b,window.innerWidth/settings.scale)-a.outerWidth(),d=Math.min(d,window.innerHeight/settings.scale)-a.outerHeight(),dkiUA.isIE()&&(b*=settings.scale,d*=
settings.scale,a.css({transform:"scale("+settings.scale+")","transform-origin":"0 0"})),a.css({top:d,left:b,bottom:"auto",right:"auto"}),$("#skipToNavigationWrapper").length&&$("#skipToNavigationWrapper").before(a.detach()),this.tryAgainButton&&(a=this.tryAgainButton.closest(".notification"),b=c.left+$(".bgRepeater").width()-a.outerWidth()-settings.course.parameters.submitButtonOffset.right,a.css({top:d,left:b,bottom:"auto",right:"auto"}),$("#skipToNavigationWrapper").length&&$("#skipToNavigationWrapper").before(a.detach()))}}};
d.positionSubmitButton=DKI.func.debounce(function(a){a.positionSubmitButtonImmediate()},100);var c=function(c,d,h,n){var g=function(a){var c=$("label[for\x3d'"+a.attr("id")+"']",d.pageContainer);$(".content input[type\x3d'radio']",d.pageContainer).each(function(c,b){$("label[for\x3d'"+b.id+"']").removeClass("checked");b.id!=a.attr("id")&&$(b).prop("checked",!1)});$(".input-group",d.pageContainer).removeClass("checked");a.prop("checked")?(c.addClass("checked"),c.closest(".input-group").addClass("checked")):
c.removeClass("checked");$(".input-group input:checked",d.pageContainer).each(function(){$(this).closest(".input-group").addClass("checked")})};this.question=h;this.player=c;this.strings=c.strings;this.page=d;this.behaviour=this.player.behaviour;this.inReview=this.player.inReview;this.settings=this.player.settings;this.submitted=!1;this.prePost="";this.pageContainer=this.page.pageContainer;this.questionElement=$("div[data-pagetype\x3d'question']",this.pageContainer);this.questionType=parseInt(this.questionElement.attr("data-questiontype"),
10);this.startTime=null;this.submitButton=$(".dki-submit-button");this.scoreDisplay=$(".questionScoreDisplay");this.maxSelections=parseInt(this.questionElement.attr("data-max-selections"),10);this.freeFormMaxLength=4E3;this.numAttempts=0;this.isPracticeQuestion=n;this.isSinglePage=a;"undefined"!==typeof scormAPI&&"SCORM"==scormAPI.strLMSStandard&&(this.freeFormMaxLength=255);this.getData=function(){};this.onShowReview=function(a){a()};this.showInlineFeedback=function(){};this.hasInlineFeedback=function(){return!1};
switch(this.questionType){case 1:this.getCorrectCount=$.proxy(DKI.TestQuestion.TrueFalseQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.TrueFalseQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.TrueFalseQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.TrueFalseQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.TrueFalseQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.TrueFalseQuestion.getOptionFeedback,
this);$(".trueOption_label",this.pageContainer).text(this.strings.trueOptionLabel);$(".falseOption_label",this.pageContainer).text(this.strings.falseOptionLabel);break;case 2:this.getCorrectCount=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.scoreOption,
this);this.calculate=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.getOptionFeedback,this);this.randomizeOptions=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.randomizeOptions,this);this.inReview||this.randomizeOptions();break;case 3:this.getCorrectCount=$.proxy(DKI.TestQuestion.FreeFormQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.FreeFormQuestion.getOptions,this);this.hasSelection=
$.proxy(DKI.TestQuestion.FreeFormQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.FreeFormQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.FreeFormQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.FreeFormQuestion.getOptionFeedback,this);break;case 4:this.getCorrectCount=$.proxy(DKI.TestQuestion.FillBlanksQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.FillBlanksQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.FillBlanksQuestion.hasSelection,
this);this.scoreOption=$.proxy(DKI.TestQuestion.FillBlanksQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.FillBlanksQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.FillBlanksQuestion.getOptionFeedback,this);break;case 5:this.getCorrectCount=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.hasSelection,
this);this.scoreOption=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.getOptionFeedback,this);this.randomizeOptions=function(){$(".dki-multiPulldownOption-element select",this.pageContainer).each(function(){for(var a=[],c=this.options.length-1;0<=c;c--)""!=$(this.options[c]).html()&&a.push(this.options[c]),this.remove(c);for(c=
a.length;c--;){var b=Math.floor(Math.random()*(c+1)),d=a[c];a[c]=a[b];a[b]=d}this.innerHTML="";if(dkiUA.ie&&8>=dkiUA.ieVersion)for(this.add(new Option("","")),c=0;c<a.length;c++)this.add(a[c],c+1);else for(this.add(new Option("",""),null),c=0;c<a.length;c++)this.add(a[c],null);this.selectedIndex=0})};this.randomizeOptions();break;case 6:this.getCorrectCount=$.proxy(DKI.TestQuestion.DragDropQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.DragDropQuestion.getOptions,this);this.hasSelection=
$.proxy(DKI.TestQuestion.DragDropQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.DragDropQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.DragDropQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.DragDropQuestion.getOptionFeedback,this);break;case 7:this.getCorrectCount=$.proxy(DKI.TestQuestion.customQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.customQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.customQuestion.hasSelection,
this);this.scoreOption=$.proxy(DKI.TestQuestion.customQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.customQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.customQuestion.getOptionFeedback,this);break;case 8:this.getCorrectCount=$.proxy(DKI.TestQuestion.captureQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.captureQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.captureQuestion.hasSelection,this);this.scoreOption=
$.proxy(DKI.TestQuestion.captureQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.captureQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.captureQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.captureQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.captureQuestion.onShowReview,this);this.getBodyText=$.proxy(DKI.TestQuestion.captureQuestion.getBodyText,this);break;case 9:this.getCorrectCount=$.proxy(DKI.TestQuestion.imageMapQuestion.getCorrectCount,
this);this.getOptions=$.proxy(DKI.TestQuestion.imageMapQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.imageMapQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.imageMapQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.imageMapQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.imageMapQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.imageMapQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.imageMapQuestion.onShowReview,
this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.imageMapQuestion.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.imageMapQuestion.hasInlineFeedback,this);this.getBodyText=$.proxy(DKI.TestQuestion.imageMapQuestion.getBodyText,this);break;case 10:this.getCorrectCount=$.proxy(DKI.TestQuestion.scenarioQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.scenarioQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.scenarioQuestion.hasSelection,
this);this.scoreOption=$.proxy(DKI.TestQuestion.scenarioQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.scenarioQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.scenarioQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.scenarioQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.scenarioQuestion.onShowReview,this);this.getBodyText=$.proxy(DKI.TestQuestion.scenarioQuestion.getBodyText,this);this.showDefaultSubmit=$.proxy(b.showDefaultSubmit,
this);break;case 11:this.getCorrectCount=$.proxy(DKI.TestQuestion.matchingQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.matchingQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.matchingQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.matchingQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.matchingQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.matchingQuestion.getOptionFeedback,this);this.getData=
$.proxy(DKI.TestQuestion.matchingQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.matchingQuestion.onShowReview,this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.matchingQuestion.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.matchingQuestion.hasInlineFeedback,this);this.getFeedbackConfig=$.proxy(DKI.TestQuestion.matchingQuestion.getFeedbackConfig,this);this.getBodyText=$.proxy(DKI.TestQuestion.matchingQuestion.getBodyText,this);break;case 12:this.getCorrectCount=
$.proxy(DKI.TestQuestion.sequencingQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.sequencingQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.sequencingQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.sequencingQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.sequencingQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.sequencingQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.sequencingQuestion.getData,
this);this.onShowReview=$.proxy(DKI.TestQuestion.sequencingQuestion.onShowReview,this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.sequencingQuestion.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.sequencingQuestion.hasInlineFeedback,this);this.getFeedbackConfig=$.proxy(DKI.TestQuestion.sequencingQuestion.getFeedbackConfig,this);this.getBodyText=$.proxy(DKI.TestQuestion.sequencingQuestion.getBodyText,this);break;case 13:this.getCorrectCount=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getCorrectCount,
this);this.getOptions=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getData,
this);this.onShowReview=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.onShowReview,this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.hasInlineFeedback,this);this.getBodyText=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getBodyText,this);break;case 14:this.getCorrectCount=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.getCorrectCount,this),
this.getOptions=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.getOptions,this),this.hasSelection=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.hasSelection,this),this.scoreOption=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.scoreOption,this),this.calculate=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.calculate,this),this.getOptionFeedback=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.getOptionFeedback,this),this.getData=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.getData,
this),this.onShowReview=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.onShowReview,this),this.showInlineFeedback=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.showInlineFeedback,this),this.hasInlineFeedback=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.hasInlineFeedback,this),this.getBodyText=$.proxy(DKI.TestQuestion.FillInTheBlanksQuestionWidget.getBodyText,this)}this.player.questionPage=this;var f=this;$(this.pageContainer).on(this.settings.clickEvent,".dki-trueFalse-selector, .dki-multiChoice-selector, .dki-multiChoiceOption-element .dki-element-anchor, .dki-trueFalseOption-element .dki-element-anchor, .dki-multiChoiceOption-element input, .dki-multiChoiceOption-element label, .dki-trueFalseOption-element input",
function(a){var c=$(this).parent().find("input");if(c.prop("disabled"))return a.stopPropagation(),a.preventDefault(),!1;var d=$("label[for\x3d'"+c.attr("id")+"']",f.pageContainer);if(!d.hasClass("checked")&&b.atMaxOptions.call(f)&&"radio"!=c.attr("type"))return alert(f.strings.tstchoicesLabel1+" "+f.maxSelections+" "+f.strings.tstchoicesLabel2),a.stopPropagation(),a.preventDefault(),c.prop("checked",c.attr("attr-checked")&&"true"==c.attr("attr-checked").toString()),!1;c.attr("attr-checked")&&"true"==
c.attr("attr-checked").toString()?"checkbox"==c.attr("type")&&c.attr("attr-checked",!1):c.attr("attr-checked",!0);c.prop("checked",c.attr("attr-checked")&&"true"==c.attr("attr-checked").toString());g(c);var e=$(this).closest(".dki-authoring-element");$("*[tabindex]:not([tabindex\x3d'-1'])",e).focus();"checkbox"!=c.attr("type")||c[0]!=a.target&&d[0]!=a.target||a.stopPropagation()});$(".dki-freeFormOption-element textarea").attr("maxlength",this.freeFormMaxLength);$(this.pageContainer).on("keyup",".dki-freeFormOption-element textarea",
function(a){a=$(this).val();a.length>f.freeFormMaxLength&&(a=a.substr(0,f.freeFormMaxLength),$(this).val(a))});$("input",this.pageContainer).on("focus",function(a){$(this).closest(".input-group-addon").addClass("focus-within")});$("input",this.pageContainer).on("blur",function(a){$(".input-group-addon.focus-within").removeClass("focus-within")});for(var m in DKI.Events.TestQuestion)$(this.pageContainer).off(DKI.Events.TestQuestion[m]);$(this.pageContainer).on(DKI.Events.TestQuestion.submitted,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.submitted,
f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.correct,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.correct,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.incorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.incorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.partiallyCorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.partiallyCorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.attemptSubmitted,
function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.attemptSubmitted,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.attemptIncorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.attemptIncorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.attemptPartiallyCorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.attemptPartiallyCorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.questionInReview,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.questionInReview,
f.page)});$(document).on(DKI.Events.TestQuestion.retry,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.retry,f.page)});$.each(this.page,function(a){"undefined"==typeof f[a]&&DKI.isFunction(this)&&(f[a]=$.proxy(f.page[a],f.page))})};DKI.applyIf(c.prototype,d);return c}();
DKI.TestQuestion.TrueFalseQuestion={calculate:function(a,b,d){return 1>b?0:100},getCorrectCount:function(){return 1},getOptions:function(){for(var a=$(".dki-trueFalseOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var k=$("input",a[c])[0];d=parseInt(k.getAttribute("data-order"),"10")-1;for(var e=null,h=0;h<this.question.options.length;h++)if(this.question.options[h].element_id==$(a[c]).data("id")){e=this.question.options[h];break}b[d]=new DKI.TestQuestion.TrueFalseOption(k,a[c],e)}return b},
getOptionFeedback:function(){return""},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(1==a[b].value())return!0;return!1}};
DKI.TestQuestion.TrueFalseOption=function(a,b,d){this.optionElement=a;this.optionValue=$(a).next();this.wrapper=b;this.choice=d;this.getFeedback=function(){return""};this.correctResponse=function(a){if(null!=a&&void 0!=a)$(this.optionElement).data("correctresponse",a.correct);else return $(this.optionElement).data("correctresponse")};this.isCorrect=function(){return this.choice.parameters.correct};this.enabled=function(a){if(void 0!==a&&null!==a)this.optionElement.disabled=!a,$(this.optionElement).closest(".input-group-addon")[a?
"removeClass":"addClass"]("disabled-option");else return!this.optionElement.disabled};this.value=function(a){if(void 0!==a&&null!==a)1==a||1==a?(this.optionElement.checked=!0,$("label,.input-group",this.wrapper).addClass("checked")):(this.optionElement.checked=!1,$("label,.input-group",this.wrapper).removeClass("checked"));else return this.optionElement.checked?1:0};this.score=function(){return 1==this.value()&&this.isCorrect()?this.value():0};this.showCorrect=function(a){1==this.value()&&this.isCorrect()?
($(".dki-authoring-content-wrapper",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&($(".dki-authoring-content-wrapper",this.wrapper).attr("title",settings.correctChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$("label",this.wrapper).text()+". "+settings.correctChoiceText+"\x3c/div\x3e")))):1==this.value()&&($(".dki-authoring-content-wrapper",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&($(".dki-authoring-content-wrapper",
this.wrapper).attr("title",settings.incorrectChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$("label",this.wrapper).text()+". "+settings.incorrectChoiceText+"\x3c/div\x3e"))));a&&this.isCorrect()&&$(".dki-authoring-content-wrapper",this.wrapper).addClass("multiChoiceCorrectResponse")};this.reset=function(){$(".dki-authoring-content-wrapper",this.wrapper).removeClass("correct").removeClass("incorrect").removeClass("multiChoiceCorrectResponse").removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();
$(this.optionElement).prop("checked",!1);$(this.optionElement).attr("attr-checked",!1);"none"!=$(this.optionElement).css("display")&&($(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex),this.optionElement.tabIndex=-1);this.optionValue.removeClass("checked");var a=$(this.optionElement).closest(".input-group");a[0]&&a.removeClass("checked").find(".checked").removeClass("checked");this.enabled(!0)};this.start=function(){"none"!=$(this.optionElement).css("display")&&(this.optionElement.tabIndex=
$(".dki-element-anchor",this.wrapper).data("tabIndex"),$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1))}};
DKI.TestQuestion.MultipleChoiceQuestion={calculate:function(a,b,d){return d>b?0:(b-d)/a*100},getCorrectCount:function(){for(var a=0,b=this.getOptions(),d=0;d<b.length;d++)b[d].choice.parameters.correct&&a++;return a},getOptions:function(){for(var a=$(".dki-multiChoiceOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var k=$("input",a[c])[0];d=parseInt(k.getAttribute("data-order"),"10")-1;for(var e=null,h=0;h<this.question.options.length;h++)if(this.question.options[h].element_id==$(a[c]).data("id")){e=
this.question.options[h];break}b[d]=new DKI.TestQuestion.MultipleChoiceOption(k,a[c],e)}return b},randomizeOptions:function(){for(var a=$(".dki-multiChoiceOption-element[data-randomized\x3d'true']",this.pageContainer),b=[],d=[],c=[],k=[],e=this.getOptions(),h=0;h<e.length;h++)e[h].wrapper.data("randomized")&&k.push(h);$.each(a,function(a,c){var e=settings.responsive?0:$(c).data("y"),k=settings.responsive?0:$(c).data("x");b[a]={top:e,left:k,numbering:$(c).find(".optionNumber").text(),key:a};$(c).before("\x3cdiv class\x3d'RandomPlaceHolder' id\x3d'RandomPlaceHolder"+
a+"'\x3e\x3c/div\x3e");d[a]=$(c).detach()});a=d.length;for(h=0;h<a;h++)c.push(d.splice(Math.floor(Math.random()*d.length),1)[0]);for(h=0;h<a;h++)$(c[h]).data("y",b[h].top).data("x",b[h].left).data("numbering",b[h].numbering).data("feedbackOrder",k[h]+1).css({left:b[h].left,top:b[h].top}),$(".optionNumber",c[h]).text(b[h].numbering),$("#RandomPlaceHolder"+b[h].key,this.pageContainer).before(c[h]);$(".RandomPlaceHolder",this.pageContainer).remove();$(".dki-multiChoiceOption-element .multiChoiceContentWrapper").css("visibility",
"")},getOptionFeedback:function(){for(var a="",b=this.getOptions(),d=[],c=0;c<b.length;c++){var k;k=b[c].wrapper.data("randomized")?parseInt(b[c].wrapper.data("feedbackOrder"),"10"):parseInt(b[c].optionElement.getAttribute("data-order"),"10");d[k-1]=b[c]}for(c=0;c<d.length;c++)this.question.include_selection_feedback&&1==d[c].value().checked?a+=d[c].getFeedback():this.question.include_correct_feedback&&d[c].isCorrect()?a+=d[c].getFeedback():this.question.include_incorrect_feedback&&!d[c].isCorrect()&&
(a+=d[c].getFeedback());return a},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(1==a[b].value().checked)return!0;return!1}};
DKI.TestQuestion.MultipleChoiceOption=function(a,b,d){this.optionElement=a;this.optionValue=$(a).next();this.wrapper=$(b);this.choice=d;this.getFeedback=function(){var a="",b=this.wrapper.data("feedback");if(b){var b=b.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),d=$(".optionNumber",this.wrapper).text();""==d&&(d="\x26bull;\x26nbsp;");a=a+"\x3cdiv class\x3d'optionFeedbackWrapper'\x3e\x3cspan class\x3d'optionFeedbackNumbering'\x3e"+d+"\x3c/span\x3e\x3cspan class\x3d'optionFeedbackContent'\x3e";
a+=b;a+="\x3c/span\x3e";a+="\x3c/div\x3e"}return a};this.correctResponse=function(a){if(null!=a&&void 0!=a)this.optionElement.setAttribute("data-correctresponse",a.correct);else return this.optionElement.getAttribute("data-correctresponse")};this.isCorrect=function(){return this.choice.parameters.correct};this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a,$(this.optionElement).closest(".input-group-addon")[a?"removeClass":"addClass"]("disabled-option");else return!this.optionElement.disabled};
this.value=function(a){if(null!==a&&void 0!==a){if(1==a.checked?(this.optionElement.checked=!0,$(".input-group, label",this.wrapper).addClass("checked")):(this.optionElement.checked=!1,$(".input-group, label",this.wrapper).removeClass("checked")),this.wrapper.data("randomized")){var b=$("#"+a.elementIdReplaced+"_wrapper");this.wrapper.css({left:b.data("x"),top:b.data("y")});$(".optionNumber",this.wrapper).text(b.data("numbering"));this.wrapper.data("feedbackOrder",a.feedbackOrder)}}else return a=
{text:this.choice.content,plainText:$("\x3cdiv\x3e").html(this.choice.content).text().trim(),elementIdReplaced:null,feedbackOrder:null},this.wrapper.data("randomized")&&(a.elementIdReplaced=this.wrapper.data("elementIdReplaced"),a.feedbackOrder=this.wrapper.data("feedbackOrder")),a.checked=this.optionElement.checked?1:0,a};this.score=function(){return 1==this.value().checked&&this.isCorrect()?1:1!=this.value().checked||this.isCorrect()?0:-1};this.showCorrect=function(a){1==this.value().checked&&(this.isCorrect()?
($(".dki-authoring-content-wrapper",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&($(".dki-authoring-content-wrapper",this.wrapper).attr("title",settings.correctChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$("label",this.wrapper).text()+". "+settings.correctChoiceText+"\x3c/div\x3e")))):($(".dki-authoring-content-wrapper",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&($(".dki-authoring-content-wrapper",
this.wrapper).attr("title",settings.incorrectChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$("label",this.wrapper).text()+". "+settings.inorrectChoiceText+"\x3c/div\x3e")))));a&&this.isCorrect()&&$(".dki-authoring-content-wrapper",this.wrapper).addClass("multiChoiceCorrectResponse")};this.reset=function(){$(".dki-authoring-content-wrapper",this.wrapper).removeClass("correct").removeClass("incorrect").removeClass("multiChoiceCorrectResponse").removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();
$(this.optionElement).prop("checked",!1);"none"!=$(this.optionElement).css("display")&&($(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex),this.optionElement.tabIndex=-1);this.optionValue.removeClass("checked");$(this.optionElement).attr("attr-checked",!1);$(".optionNumber",this.wrapper).text(this.wrapper.data("numbering"));this.wrapper.data("feedbackOrder",null);this.wrapper.data("elementIdReplaced",null);var a=$(this.optionElement).closest(".input-group");a[0]&&a.removeClass("checked").find(".checked").removeClass("checked");
this.enabled(!0)};this.start=function(){"none"!=$(this.optionElement).css("display")&&(this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex"),$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1))}};
DKI.TestQuestion.FillBlanksQuestion={calculate:function(a,b,d){return b/a*100},getCorrectCount:function(){return this.getOptions().length},getOptions:function(){for(var a=$(".dki-fillBlanksOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var k=$("input",a[c])[0];d=parseInt(k.getAttribute("data-order"),"10")-1;for(var e=null,h=0;h<this.question.options.length;h++)if(this.question.options[h].element_id==$(a[c]).data("id")){e=this.question.options[h];break}b[d]=new DKI.TestQuestion.FillBlanksOption(k,
$(a[c]),e)}return b},getOptionFeedback:function(){for(var a="",b=this.getOptions(),d=0;d<b.length;d++)this.question.include_correct_feedback&&1==b[d].score()?a+=b[d].getFeedback():this.question.include_incorrect_feedback&&0==b[d].score()&&(a+=b[d].getFeedback());return a},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(""==a[b].value())return!1;return!0}};
DKI.TestQuestion.FillBlanksOption=function(a,b,d){this.optionElement=a;this.wrapper=b;this.choice=d;this.getFeedback=function(){var a="",b=this.wrapper.data("feedback");if(b){var b=b.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),d=$(".optionNumber",this.wrapper).text();""==d&&(d="\x26bull;\x26nbsp;");a=a+"\x3cdiv class\x3d'optionFeedbackWrapper'\x3e\x3cspan class\x3d'optionFeedbackNumbering'\x3e"+d+"\x3c/span\x3e\x3cspan class\x3d'optionFeedbackContent'\x3e";
a+=b;a+="\x3c/span\x3e";a+="\x3c/div\x3e"}return a};this.correctResponse=function(a){if(null!=a&&void 0!=a)this.optionElement.setAttribute("data-correctresponse",a.correctValues);else return this.optionElement.getAttribute("data-correctresponse")};this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!==a)$(this.optionElement).val(a);else return $.trim($(this.optionElement).val()).toLowerCase()};
this.isCorrect=function(){return 1==this.score()?!0:!1};this.score=function(){for(var a=this.choice.parameters.correctValues,b=0;b<a.length;b++){var d=$.trim(a[b]).toLowerCase(),h=this.value();$.isNumeric(d)&&(d=parseFloat(d),h=parseFloat(h.replace(/\,|\s/g,"")));d=$("\x3cspan\x3e"+d+"\x3c/span\x3e").text().trim();if(h==d)return 1}return 0};this.showCorrect=function(a){1==this.score()?($(".dki-question-option",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&$(".dki-question-option",
this.wrapper).attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.correctChoiceText+"\x3c/div\x3e"))):($(".dki-question-option",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.incorrectChoiceText+
"\x3c/div\x3e")))};this.reset=function(){$(this.optionElement).val("");$(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex);this.optionElement.tabIndex=-1;$(".dki-question-option",this.wrapper).removeClass("correct");$(".dki-question-option",this.wrapper).removeClass("incorrect");$(".dki-question-option",this.wrapper).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};this.start=function(){this.optionElement.tabIndex=$(".dki-element-anchor",
this.wrapper).data("tabIndex");$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1)}};
DKI.TestQuestion.MultiplePulldownQuestion={calculate:function(a,b,d){return b/a*100},getCorrectCount:function(){return this.getOptions().length},getOptions:function(){for(var a=$(".dki-multiPulldownOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var k=$("select",a[c])[0];d=parseInt(k.getAttribute("data-order"),"10")-1;for(var e=null,h=0;h<this.question.options.length;h++)if(this.question.options[h].element_id==$(a[c]).data("id")){e=this.question.options[h];break}b[d]=new DKI.TestQuestion.MultiplePulldownOption(k,
$(a[c]),e)}return b},getOptionFeedback:function(){for(var a="",b=this.getOptions(),d=0;d<b.length;d++)this.question.include_correct_feedback&&1==b[d].score()?a+=b[d].getFeedback():this.question.include_incorrect_feedback&&0==b[d].score()&&(a+=b[d].getFeedback());return a},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(""==a[b].value())return!1;return!0}};
DKI.TestQuestion.MultiplePulldownOption=function(a,b,d){this.optionElement=a;this.wrapper=b;this.choice=d;this.getFeedback=function(){var a="",b=this.wrapper.data("feedback");if(b){var b=b.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),d=$(".optionNumber",this.wrapper).text();""==d&&(d="\x26bull;\x26nbsp;");a=a+"\x3cdiv class\x3d'optionFeedbackWrapper'\x3e\x3cspan class\x3d'optionFeedbackNumbering'\x3e"+d+"\x3c/span\x3e\x3cspan class\x3d'optionFeedbackContent'\x3e";
a+=b;a+="\x3c/span\x3e";a+="\x3c/div\x3e"}return a};this.correctResponse=function(a){if(null!=a&&void 0!=a)this.optionElement.setAttribute("data-correctresponse",a.correctValue);else return this.optionElement.getAttribute("data-correctresponse")};this.isCorrect=function(){var a=$('\x3cselect\x3e\x3coption value\x3d"'+escape(this.choice.parameters.correctValue.trim())+'"\x3e'+this.choice.parameters.correctValue+"\x3c/option\x3e\x3c/select\x3e");return escape(this.value().trim())==a.value()?!0:!1};
this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!=a)$(this.optionElement).val(a);else return $(this.optionElement).val()};this.score=function(){return this.isCorrect()?1:0};this.showCorrect=function(a){1==this.score()?($(".dki-question-option",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$(this.optionElement).val()+". "+settings.correctChoiceText+"\x3c/div\x3e"))):($(".dki-question-option",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){this.optionElement.selectedIndex=0;$(".dki-element-anchor",this.wrapper).attr("tabIndex",
this.optionElement.tabIndex);this.optionElement.tabIndex=-1;$(".dki-question-option",this.wrapper).removeClass("correct");$(".dki-question-option",this.wrapper).removeClass("incorrect");$(".dki-question-option",this.wrapper).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};this.start=function(){this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex");$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1)}};
DKI.TestQuestion.FreeFormQuestion={calculate:function(){return""!==this.getOptions()[0].value().trim()?100:0},getCorrectCount:function(){return 0},getOptions:function(){for(var a=$(".dki-freeFormOption-element textarea",this.pageContainer),b=[],d,c=0;c<a.length;c++)d=parseInt(a[c].getAttribute("data-order"),"10")-1,b[d]=new DKI.TestQuestion.FreeFormOption(a[c],$(a[c]).closest(".dki-authoring-element"));return b},getOptionFeedback:function(){return""},hasSelection:function(){for(var a=this.getOptions(),
b=0;b<a.length;b++)if(""==a[b].value())return!1;return!0}};
DKI.TestQuestion.FreeFormOption=function(a,b){this.optionElement=a;this.wrapper=b;this.correctResponse=function(){return""};this.getFeedback=function(){return""};this.isCorrect=function(){return""!=this.value()?!0:!1};this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!==a)$(this.optionElement).val(a);else return $(this.optionElement).val()};this.score=function(){return 0};this.showCorrect=
function(a){this.isCorrect()?($(".dki-question-option",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.correctChoiceText+"\x3c/div\x3e"))):($(".dki-question-option",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$(this.optionElement).val()+". "+settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){$(this.optionElement).val("");$(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex);this.optionElement.tabIndex=-1;$(".dki-question-option",this.wrapper).removeClass("correct");$(".dki-question-option",this.wrapper).removeClass("incorrect");$(".dki-question-option",this.wrapper).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};
this.start=function(){this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex");$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1)}};
DKI.TestQuestion.DragDropQuestion={calculate:function(a,b,d){return 0==a&&0==b&&0==d?0:b/a*100},getCorrectCount:function(){return $(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).length},getOptions:function(){for(var a=$(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",
this.pageContainer),b=[],d=0;d<a.length;d++){for(var c=null,k=$(a[d]).data("id"),e=0;e<this.question.options.length;e++)this.question.options[e].element_id==k&&(c=this.question.options[e]);b[d]=new DKI.TestQuestion.DragDropOption(a[d],c)}return b},getOptionFeedback:function(){return""},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(null!=a[b].value().target.id)return!0;return!1}};
DKI.TestQuestion.customQuestion={calculate:function(a,b,d,c){try{if(isNaN(c))throw"Invalid data. Please provide a numeric score.";c=parseInt(c,10);c=0>c?0:c;return 100<c?100:c}catch(k){return 0}},getOptions:function(){return[]},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return!0}};
DKI.TestQuestion.DragDropOption=function(a,b){this.optionElement=a;this.questionOption=b;this.correctResponse=function(a){a=this.value();$(this.optionElement).css({top:a.y/a.scale+"px",left:a.x/a.scale+"px"});return null};this.getFeedback=function(){return""};this.enabled=function(a){if(null!==a&&void 0!==a){$(this.optionElement).draggable({disabled:!a});var b=0;$(".dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue],.dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",
this.pageContainer).each(function(){var a=parseInt($(this).css("z-index"),10);a>b&&(b=a)});a=$(this.optionElement).data("elementno");$(this.optionElement).css("z-index",Math.max(b+1,a));$(this.optionElement).parent(".dki-authoring-group").css("position","static")}else return!1};this.value=function(a){if(null!==a&&void 0!==a)$(this.optionElement).data("dropData",a);else{a=$(this.optionElement).data("dropData");if(!a){a=$(this.optionElement).position();var b=$(this.optionElement).data("title");""==
b&&(b=$(this.optionElement).text());a={id:$(this.optionElement).data("dragdropid"),elementId:$(this.optionElement).data("id"),title:b,target:{id:null,title:"No Target"},x:a.left,y:a.top,scale:settings.scale}}return a}};this.isCorrect=function(){return 1==this.score()?!0:!1};this.score=function(){var a=this.value().target.id;if(a){for(var b=0;b<this.questionOption.parameters.correctTargets.length;b++)if(a.toString().toLowerCase()==this.questionOption.parameters.correctTargets[b].toString().toLowerCase())return 1;
return-1}return 0<this.questionOption.parameters.correctTargets.length?-1:1};this.showCorrect=function(a){1==this.score()?($(this.optionElement).addClass("correct"),""!=settings.correctChoiceText&&$(this.optionElement).find(".dki-element-content").attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback'\x3e"+settings.correctChoiceText+"\x3c/div\x3e"))):($(this.optionElement).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(this.optionElement).find(".dki-element-content").attr("title",
settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback'\x3e"+settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){$(this.optionElement).data("dropData",null);$(this.optionElement).removeClass("correct");$(this.optionElement).removeClass("incorrect");$(this.optionElement).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};this.start=function(){}};
DKI.TestQuestion.ImageMapOption=function(a){this.mapEl=$(a.pageContainer).find("#"+a.question.options[0].elementId+"_wrapper .dki-element-content");this.test=a;return this};
DKI.TestQuestion.ImageMapOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.mapEl.ImageMap("enterReview",!0,!a,!0)},start:function(){},score:function(){return this.mapEl.data("dki.ImageMap").score()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.mapEl.ImageMap(a?"enable":"disable")},reset:function(){this.mapEl.ImageMap("reset");this.enabled(!0)}};
DKI.TestQuestion.ScenarioOption=function(a){this.scenarioEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.ScenarioOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.scenarioEl.Scenario("enterReview",!0,!a)},start:function(){},score:function(){return this.scenarioEl.data("dki.Scenario").getScore()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.scenarioEl.Scenario(a?"enable":"disable")},reset:function(){this.scenarioEl.Scenario("reset")}};
DKI.TestQuestion.MatchingQuestionOption=function(a){this.matchEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.MatchingQuestionOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.matchEl.MatchingQuestion("enterReview",!0,!a)},start:function(){},score:function(){return this.matchEl.data("dki.MatchingQuestion").score()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.matchEl.MatchingQuestion(a?"enable":"disable")},reset:function(){this.matchEl.MatchingQuestion("reset");this.enabled(!0)}};
DKI.TestQuestion.SequencingQuestionOption=function(a){this.sequenceEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.SequencingQuestionOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.sequenceEl.SequencingQuestion("enterReview",!0,!a)},start:function(){},score:function(){return this.sequenceEl.data("dki.SequencingQuestion").score()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.sequenceEl.SequencingQuestion(a?"enable":"disable")},reset:function(){this.sequenceEl.SequencingQuestion("reset");this.enabled(!0)}};
DKI.TestQuestion.captureQuestion={init:function(a){a.captureEl=$(a.pageContainer).find("#"+a.question.options[0].elementId+"_wrapper");var b=function(){return{review:a.isPracticeQuestion,retake:!a.inReview&&a.isPracticeQuestion&&a.question.show_try_again&&a.numAttempts<a.question.attempts,next:function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)}}};$(document).one(DKI.ContentPage.events.loadFinished,function(){a.captureEl.off(tryMe.EVENT.RESTART_BUTTON+".dkiTest").on(tryMe.EVENT.RESTART_BUTTON+
".dkiTest",function(){a.numAttempts+=1;a.captureEl.capture("setOption",["buttons",b()])});a.captureEl.capture("setOption",["buttons",b()]);$(document).one(DKI.Events.TestQuestion.nextClicked+" "+DKI.Events.TestQuestion.forceEnd,function(){a.captureEl.capture("cleanup")});var d=!1;if(a.isPracticeQuestion||a.canShowCorrectAnswers()&&("pre"==a.prePost&&a.behaviour.reviewPreAnswers||"post"==a.prePost&&a.behaviour.reviewPostAnswers))d=!0;a.captureEl.capture("setOption",["showCorrectAnswers",d]);d=a.canShowFeedback();
a.captureEl.capture("setOption",["showFeedback",d]);a.captureEl.off(testMe.EVENT.COMPLETE+".dkiTest").on(testMe.EVENT.COMPLETE+".dkiTest",function(b,d){a.inReview||a.submitted||a.submitQuestion(d.testMe.getScore())});d&&(d=a.question.parameters.feedback,a.captureEl.capture("setOption",["feedback",{correct:d.correct.useDefault?contentApi.getDefaultFeedbackText("correct"):d.correct.text,incorrect:d.incorrect.useDefault?contentApi.getDefaultFeedbackText("incorrect"):d.incorrect.text}]))})},onShowReview:function(a){var b=
this;this.captureEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.question.timedOut&&b.captureEl.capture("setOption",["overrideScore",0]);b.captureEl.capture("import",[b.question.data]);b.captureEl.capture("enterReview");b.captureEl.css({opacity:1,transition:"opacity 150ms linear"});a()})},calculate:function(){return this.captureEl.capture("getScore")},getData:function(){return this.captureEl.capture("export")},getOptions:function(){return[]},getOptionFeedback:function(){return""},
getCorrectCount:function(){return 0},hasSelection:function(){return!0},getBodyText:function(){var a=this.captureEl.find("#introductionText").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.imageMapQuestion={init:function(a){a.mapEl=$(a.pageContainer).find("#"+a.question.options[0].elementId+"_wrapper .dki-element-content")},onShowReview:function(a){var b=this;this.mapEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.mapEl.ImageMap("import",b.question.data);a();b.mapEl.ImageMap("enterReview",b.canShowCorrectAnswers(),!0,!0);b.mapEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(){return this.mapEl.data("dki.ImageMap").score()},
getData:function(){return this.mapEl.data("dki.ImageMap").export()},getOptions:function(){return[new DKI.TestQuestion.ImageMapOption(this)]},showInlineFeedback:function(){this.mapEl.ImageMap("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.mapEl.data("dki.ImageMap").hasInlineFeedback()},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return this.mapEl.data("dki.ImageMap").hasSelection()},
getBodyText:function(){var a=this.mapEl.find(".preamble_content").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.scenarioQuestion={init:function(a){a.scenarioEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);$(document).one(DKI.ContentPage.events.loadFinished,function(){a.scenarioEl.on("scenario.end",function(){a.inReview||a.showDefaultSubmit()})})},onShowReview:function(a){var b=this;this.scenarioEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.scenarioEl.Scenario("import",b.question.data);a();b.scenarioEl.Scenario("enterReview",
[b.canShowCorrectAnswers(),!0]);b.scenarioEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(){return this.scenarioEl.data("dki.Scenario").getScore()},getData:function(){return this.scenarioEl.data("dki.Scenario").export()},getOptions:function(){return[new DKI.TestQuestion.ScenarioOption(this)]},showInlineFeedback:function(){this.scenarioEl.Scenario("showInlineFeedback")},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return!0},
getBodyText:function(){var a=this.scenarioEl.find(".preamble_content").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.matchingQuestion={init:function(a){a.matchEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId)},onShowReview:function(a){var b=this;this.matchEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.matchEl.MatchingQuestion("import",b.question.data);a();b.matchEl.MatchingQuestion("enterReview",[b.canShowCorrectAnswers()]);b.matchEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.matchEl.data("dki.MatchingQuestion").score(!1,
!a)},getData:function(){return this.matchEl.data("dki.MatchingQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.MatchingQuestionOption(this)]},showInlineFeedback:function(){this.matchEl.MatchingQuestion("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.matchEl.data("dki.MatchingQuestion").hasInlineFeedback()},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},
hasSelection:function(){return this.matchEl.data("dki.MatchingQuestion").hasSelection()},getFeedbackConfig:function(){return this.question.parameters.feedback},getBodyText:function(){var a=this.matchEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.sequencingQuestion={init:function(a){a.sequenceEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId)},onShowReview:function(a){var b=this;this.sequenceEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.sequenceEl.SequencingQuestion("import",b.question.data);a();b.sequenceEl.SequencingQuestion("enterReview",[b.canShowCorrectAnswers()]);b.sequenceEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.sequenceEl.data("dki.SequencingQuestion").score(!1,
!a)},getData:function(){return this.sequenceEl.data("dki.SequencingQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.SequencingQuestionOption(this)]},showInlineFeedback:function(){this.sequenceEl.SequencingQuestion("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.sequenceEl.data("dki.SequencingQuestion").hasInlineFeedback()},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},
hasSelection:function(){return this.sequenceEl.data("dki.SequencingQuestion").hasSelection()},getFeedbackConfig:function(){return this.question.parameters.feedback},getBodyText:function(){var a=this.sequenceEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.matchingQuestion={init:function(a){a.matchEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId)},onShowReview:function(a){var b=this;this.matchEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.matchEl.MatchingQuestion("import",b.question.data);a();b.matchEl.MatchingQuestion("enterReview",[b.canShowCorrectAnswers()]);b.matchEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.matchEl.data("dki.MatchingQuestion").score(!1,
!a)},getData:function(){return this.matchEl.data("dki.MatchingQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.MatchingQuestionOption(this)]},showInlineFeedback:function(){this.matchEl.MatchingQuestion("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.matchEl.data("dki.MatchingQuestion").hasInlineFeedback()},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},
hasSelection:function(){return this.matchEl.data("dki.MatchingQuestion").hasSelection()},getFeedbackConfig:function(){return this.question.parameters.feedback},getBodyText:function(){return this.matchEl.find(".question-description").text()}};
DKI.TestQuestion.sequencingQuestion={init:function(a){a.sequenceEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId)},onShowReview:function(a){var b=this;this.sequenceEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.sequenceEl.SequencingQuestion("import",b.question.data);a();b.sequenceEl.SequencingQuestion("enterReview",[b.canShowCorrectAnswers()]);b.sequenceEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.sequenceEl.data("dki.SequencingQuestion").score(!1,
!a)},getData:function(){return this.sequenceEl.data("dki.SequencingQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.SequencingQuestionOption(this)]},showInlineFeedback:function(){this.sequenceEl.SequencingQuestion("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.sequenceEl.data("dki.SequencingQuestion").hasInlineFeedback()},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},
hasSelection:function(){return this.sequenceEl.data("dki.SequencingQuestion").hasSelection()},getFeedbackConfig:function(){return this.question.parameters.feedback},getBodyText:function(){return this.sequenceEl.find(".question-description").text()}};
DKI.TestQuestion.MultipleChoiceQuestionWidget={init:function(a){requirejs(["questionElement"],function(){a.questionEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);setTimeout(function(){a.questionEl.data("dki.MultipleChoiceQuestion").setTestConfig({attempts:a.question.attempts,allowInlineFeedback:!1,showCorrectAtEnd:!1})},10)})},onShowReview:function(a){this.questionEl=$(this.pageContainer).find("#content_"+this.question.options[0].elementId);var b=this;this.questionEl.css({opacity:0,
transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.questionEl.data("dki.MultipleChoiceQuestion").import(b.question.data);a();b.canShowGivenAnswers()&&b.questionEl.data("dki.MultipleChoiceQuestion").showGivenAnswers();b.canShowCorrectAnswers()&&b.questionEl.data("dki.MultipleChoiceQuestion").showCorrectAnswers();b.questionEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.questionEl.data("dki.MultipleChoiceQuestion").scoreQuestion(!1,
!a,!0)},getData:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.MultipleChoiceQuestionWidgetOption(this)]},showInlineFeedback:function(){this.questionEl.data("dki.MultipleChoiceQuestion").scoreQuestion(!0,!0)},hasInlineFeedback:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").hasInlineFeedback()},getOptionFeedback:function(){var a=this,b=this.questionEl.data("dki.MultipleChoiceQuestion").getOptions(),
d="";$.each(b,function(){if(""!=this.parameters.config.feedback){var b=this.parameters.config.feedback.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),k=a.questionEl.find(".dki-authoring-element-element[data-id\x3d"+this.id+"]"),e=a.questionEl.data("dki.MultipleChoiceQuestion"),h=k.find("input").is(":checked")&&e.options.outline.parameters.config.feedback.showLearnerSelections,n=this.parameters.config.correct&&e.options.outline.parameters.config.feedback.showCorrectChoices,
e=!this.parameters.config.correct&&e.options.outline.parameters.config.feedback.showIncorrectChoices;if(h||n||e)k=$(".numbering",k).text(),""==k&&(k="\x26bull;\x26nbsp;"),d+="\x3cdiv class\x3d'optionFeedbackWrapper'\x3e",d+="\x3cspan class\x3d'optionFeedbackNumbering'\x3e",d+=k,d+="\x3c/span\x3e",d+="\x3cspan class\x3d'optionFeedbackContent'\x3e",d+=b,d+="\x3c/span\x3e",d+="\x3c/div\x3e"}});return d},getCorrectCount:function(){return 0},hasSelection:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").hasSelection()},
getBodyText:function(){var a=this.questionEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};DKI.TestQuestion.MultipleChoiceQuestionWidgetOption=function(a){this.questionEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.MultipleChoiceQuestionWidgetOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.questionEl.data("dki.MultipleChoiceQuestion").showGivenAnswers();a&&this.questionEl.data("dki.MultipleChoiceQuestion").showCorrectAnswers()},start:function(){},score:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").scoreQuestion(!1,!0)},value:function(){return""},correctResponse:function(){},enabled:function(a){a?this.questionEl.data("dki.MultipleChoiceQuestion").enableInputs():
this.questionEl.data("dki.MultipleChoiceQuestion").disableInputs()},reset:function(){this.questionEl.data("dki.MultipleChoiceQuestion").reset();this.enabled(!0)}};
DKI.TestQuestion.FillInTheBlanksQuestionWidget={init:function(a){requirejs(["questionElement"],function(){a.questionEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);setTimeout(function(){a.questionEl.data("dki.FillInTheBlanksQuestion").setTestConfig({attempts:a.question.attempts,allowInlineFeedback:!1,showCorrectAtEnd:!1})},10)})},onShowReview:function(a){this.questionEl=$(this.pageContainer).find("#content_"+this.question.options[0].elementId);var b=this;this.questionEl.css({opacity:0,
transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.questionEl.data("dki.FillInTheBlanksQuestion").import(b.question.data);b.questionEl.data("dki.FillInTheBlanksQuestion").showGivenAnswers();a();b.questionEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.questionEl.data("dki.FillInTheBlanksQuestion").scoreQuestion(!1,!a,!0)},getData:function(){return this.questionEl.data("dki.FillInTheBlanksQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.FillInTheBlanksQuestionWidgetOption(this)]},
showInlineFeedback:function(){this.questionEl.data("dki.FillInTheBlanksQuestion").scoreQuestion(!0,!0)},hasInlineFeedback:function(){return this.questionEl.data("dki.FillInTheBlanksQuestion").hasInlineFeedback()},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return this.questionEl.data("dki.FillInTheBlanksQuestion").hasSelection()},getBodyText:function(){var a=this.questionEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",
this.pageContainer).text());return a}};DKI.TestQuestion.FillInTheBlanksQuestionWidgetOption=function(a){this.questionEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.FillInTheBlanksQuestionWidgetOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.questionEl.data("dki.FillInTheBlanksQuestion").showGivenAnswers();a&&this.questionEl.data("dki.FillInTheBlanksQuestion").showCorrectAnswers()},start:function(){},score:function(){return this.questionEl.data("dki.FillInTheBlanksQuestion").scoreQuestion(!1,!0)},value:function(){return""},correctResponse:function(){},enabled:function(a){a?this.questionEl.data("dki.FillInTheBlanksQuestion").enableInputs():
this.questionEl.data("dki.FillInTheBlanksQuestion").disableInputs()},reset:function(){this.questionEl.data("dki.FillInTheBlanksQuestion").reset();this.enabled(!0)}};