/*! -- File: tryMe.js ( Input 0 ) -- */
var tryMe=function(a){this.options=$.extend({},tryMe.DEFAULTS,a);this.state={currentStepValidated:!1,dragging:!1,fullscreen:!1,overallStep:0,totalClicks:0,totalTime:0,prevClicks:0,prevTime:0,restartButtonEnabled:!1,switchingSections:!1,hintButtonEnabled:!1,infoIconDisabled:!1,started:!1,steps:[],completedSteps:[],restarting:!1,isPaused:!1,tooltipsRepositioned:!1,secondaryPathReturns:[],FullscreenTransition:!1,playerHead:new TwoDimensionalPosition};return this.init()};
tryMe.CONST=Object.freeze({ENTER_BUTTON:13,TAB_BUTTON:9,SECTION_TYPES:{SECTION:{showByDefault:!0},ALTERNATIVE_PATH:{showByDefault:!1},BRANCH:{showByDefault:!1}},PANEL_TYPES:{BASIC:{priority:0},WITH_CALLBACK:{priority:2},FROM_STEP:{priority:1}}});
tryMe.DEFAULTS={FADE_TIME:500,FADE_MULTIPLIER:5,MIN_HINT_TEXT_WIDTH:150,HINT_TEXT_MARGIN:10,TOOLTIP_THEME:"tooltipster-capture",mobile:!1,scale:function(){return 1},STRINGS:{INCORRECT_ATTEMPT:"Incorrect Attempt",CORRECT:"Correct Answer",INCORRECT:"Incorrect Answer",CONTINUE:"Continue",NEXT:"Next",FINISH:"Finish",OK:"Ok",SHOW_HINT:"Show Hint",FEEDBACK_FEEDBACK_LABEL:"Feedback",FEEDBACK_STEP_LABEL:"Step",FEEDBACK_TYPED_YOU_TYPED:"You Typed",RESTART_TEXT:"Steps completed",ARIA_LABEL_DECISION:"Decision step frame",
ARIA_LABEL_DECISION_INSTRUCTION:"Decision step instructions",ARIA_LABEL_DECISION_OPTIONS:"Decision step options",ARIA_LABEL_INTRODUCTION:"Scene Introduction",ARIA_LABEL_SUMMARY:"Scene summary",ARIA_LABEL_GLOSSARY:"Glossary definition"}};tryMe.EVENT={START:"tryMe.play",RESTART:"tryMe.pause",STEP_CHANGED:"tryMe.stepChanged",STEP_FINISHED:"tryMe.stepFinished",HINT:"tryMe.showHint",ASSESSMENT_CHANGED:"tryMe.assessmentChanged",RESTART_BUTTON:"tryMe.restart",COMPLETE:"tryMe.complete"};
tryMe.CAPTURE_EVENT={TYPED:"TYPED",DRAG_START:"START_MOUSE_DRAGGED",DRAG_FINISH:"FINISH_MOUSE_DRAGGED",CLICK:"MOUSE_CLICKED",BUTTON_PRESSED:"BUTTON_PRESSED",KEY_COMBO:"KEY_COMBINATION",SPECIAL_KEY:"SPECIAL_KEY",EXPLANATION:"EXPLANATION",SELECT:"SELECT",DECISION:"DECISION",ALTERNATIVE_PATH:"ALTERNATIVE_PATH",BRANCH:"BRANCH",STOP:"STOP_CAPTURE",NEXT_STEP:"NEXT_STEP",USER_REQUEST:"USER_REQUEST"};
tryMe.prototype={sideContainerScrollParentSelector:".panel",init:function(){this.$container=this.options.container;for(var a=0;a<this.options.sections.length;a++)for(var b=0;b<this.options.sections[a].steps.length;b++)this.state.steps.push(this.getStepFactory().createStep(this.options.sections[a].steps[b],this));this.setElements();this.panelManager=this.getpanelManager(this);this.sideContainerManager=this.getSideContainerManager(this);$.each($("img.unloaded"),function(){$(this).attr("src",$(this).data("src"));
$(this).removeClass("unloaded")});this.$elements.carousel.on("contextmenu",function(a){a.preventDefault()});this.$elements.carousel.find(".item:first").addClass("active");this.resizeSideContainer();this.updateList();this.state.resizeInterval=setInterval($.proxy(this.resizeSideContainer,this),1E3);this.$elements.dragOverlay.hide();this.initializeHandlers();this.eventListeners();this.state.initializing=!1;this.state.assessTimer=setInterval($.proxy(function(){this.state.totalTime+=1},this),1E3);this.options.transformScale||
(this.options.transformScale=1);this.state.playerHead.set(1,1);var c=this;this.$container.on(tryMe.EVENT.STEP_CHANGED,function(a,b){c.state.playerHead.set(b.x,b.y)});return this},reset:function(a){if(a||this.started)this.$container.trigger(tryMe.EVENT.RESTART_BUTTON,this),this.$elements.startScreen.show().find(".btn").enable();this.$container.find(".tooltipstered").tooltipster("destroy")},setElements:function(){this.$elements={sectionInfo:this.$container.find("#sectionInfo"),carousel:this.$container.find("#softwareSimCarousel"),
carouselContainer:this.$container.find("#tryMeContainer"),hotspot:this.$container.find(".targetHotspot"),dragOverlay:this.$container.find("#tryMeDragOverlay"),hintButton:this.$container.find("#hintButton"),sideContainer:this.$container.find("#tryMeSideContainer"),infoScreen:this.$container.find("#tryMeInfoScreen"),startScreen:this.$container.find("#startScreen"),continueScreen:this.$container.find(".continue"),tooltipTemplate:this.$container.find("#tooltipTemplate"),GenericPanelOverlay:this.$container.find("#generalPanelOverlay"),
GenericPanelContentContainer:this.$container.find("#generalPanelContentContainer")}},eventListeners:function(){var a=this;this.$container.on(tryMe.EVENT.RESTART_BUTTON,function(){a.state.started=!1;a.state.restartButtonEnabled=!1;a.getCurrentStepObj()&&a.getCurrentStepObj().discardResources();a.state.overallStep=0;a.$elements.sideContainer.find(".active .arrow-hint").removeClass("arrow-hint-active");a.toggleRestartButton();a.$elements.infoScreen.prop("disabled")||a.$elements.infoScreen.prop("disabled",
!0).fadeOut(a.options.FADE_TIME);a.getSideContainerManager(a).reset();a.state.restarting=!1})},showGeneralTextBasedPanel:function(a,b,c,d,e){if(a){var f=this;e=$("\x3cdiv class\x3d'general-container-text-package' aria-label\x3d'"+e+"'\x3e\x3c/div\x3e");var g=$("\x3cdiv class \x3d 'general-container-text-content'\x3e\x3c/div\x3e");g.html(a);a=$("\x3cdiv class\x3d'general-container-primary-action-button-div'\x3e\x3cbutton class\x3d'btn btn-primary'\x3e"+d+" \x3c/button\x3e\x3c/div\x3e");$(a).on("click",
function(){f.panelManager.closePanel();c&&c()});e.append(g);e.append(a);this.panelManager.addAndDisplayPanel(e,b)}},showGlossaryPane:function(a){a&&this.showGeneralTextBasedPanel(a,tryMe.CONST.PANEL_TYPES.BASIC,null,this.options.STRINGS.OK,this.options.STRINGS.ARIA_LABEL_GLOSSARY)},initializeHandlers:function(){var a=this;$(window).on("resize."+this.$container.attr("id"),function(){a.resizeSideContainer();a.state.currentEventType==tryMe.CAPTURE_EVENT.TYPED&&a.toggleTypingTooltip(!0)});this.$elements.carousel.find("img").on("dragstart",
function(a){a.preventDefault()});this.$elements.startScreen.find(".btn").on("click",function(){a.isEndOfPath()?(a.$elements.startScreen.fadeOut(a.options.FADE_TIME).find("button").prop("disabled",!0),a.$container.trigger(tryMe.EVENT.RESTART_BUTTON,a),a.nextStep(),a.toggleRestartAnimation(!1,currentStepObj.getRestartText())):(a.nextStep(),a.$container.trigger(tryMe.EVENT.START,a))});this.$elements.carouselContainer.find(".try-me-restart-btn").on("click",function(){$(this).trigger("blur");a.$container.trigger(tryMe.EVENT.RESTART_BUTTON,
a);a.nextStep();a.$container.trigger(tryMe.EVENT.START,a)});this.$container.on(tryMe.EVENT.START,function(){a.state.started=!0;a.state.restarting=!1;a.state.hintButtonEnabled=!0;a.toggleHintButton()});this.$container.find("#fullScreen").on("click",function(){a.toggleFullscreen()});this.$elements.hintButton.on("click",function(){a.showHint()});this.$elements.sideContainer.find("li").on("click",function(){a.sidePanelItemClicked($(this))})},sidePanelItemClicked:function(a){this.goToStep(a,!0)},getCurrentSectionFromOverallStep:function(a){var b=
-1,c=0;this.$elements.sectionInfo.find("\x3e*").each(function(d,e){e=$(this).data("section-size")||0;if(e>=a-c)return b=d+1,!1;c+=e});return b},getCurrentStepFromOverallStep:function(a){var b=-1,c=0;this.$elements.sectionInfo.find("\x3e*").each(function(){var d=$(this).data("section-size")||0;if(d>=a-c)return b=a-c,!1;c+=d});return b},getCurrentVisibleActiveStepWithSection:function(){for(var a=$("#testMeSideContainer \x3e div \x3e .list-group").children().get(),b=0,c=0;c<a.length;c++)if("DIV"===a[c].tagName)b=
0;else if("none"!==$(a[c]).css("display")&&(b++,a[c].classList.contains("active")))return b},isLastStepInSection:function(a){a=!1;for(var b=$("#testMeSideContainer \x3e div \x3e .list-group").children().get(),c=0;c<b.length;c++)if("none"!==$(b[c]).css("display")){if("DIV"===b[c].tagName&&b[c].classList.contains("current")&&!a||1===this.$elements.sectionInfo.data("number-of-sections"))a=!0;if(a&&b[c].classList.contains("active"))for(var d=c;d<b.length;d++){if(!b[d+1]||"DIV"===b[d+1].tagName||d>=b.length)return!0;
if("none"!==$(b[d+1]).css("display")||!b[d+1].classList.contains("disabled"))return!1}}return!1},getOverallStepFromSectionAndStep:function(a,b){return this.getSideContainerManager(this).fetchOverallStepFromSectionAndStep(a,b)},getCarouselItemForStep:function(a){var b=this.getCurrentStepFromOverallStep(a);a=this.getCurrentSectionFromOverallStep(a);return this.$elements.carousel.find("[data-step-count\x3d'"+b+"'][data-section-count\x3d'"+a+"']")},getHotspotForCurrentStep:function(a){var b=[],c;for(c in arguments)b.push(arguments[c]);
return this.getHotspotForStep.apply(this,[this.state.overallStep].concat(b))},getHotspotForStep:function(a,b){var c=this.getCarouselItemForStep(a);a=this.getStepObjById(a).hotSpot;b=b?1:this.getScale();return this.getHotspotScaledPositionAndDims(a,c,b)},getHotspotScaledPositionAndDims:function(a,b,c){b=this.getElementPositionOverStep(a,b,c);return{left:b.left,top:b.top,width:a.width*c,height:a.height*c}},getElementPositionOverStep:function(a,b,c){if(b[0]){var d="none"===b.css("display")?b.parent():
b;c=c||this.getScale();var e=a.minX*c,f=a.minY*c;a=b.find("img")[0].width;d.width()>a&&(e=parseFloat(e,10)+(d.width()-a)/2)}return{left:e||0,top:f||0}},getEventTypeForStep:function(a){return this.state.steps[a-1]?this.state.steps[a-1].eventType:""},stepHasTestMeInstructions:function(a){return""!==this.state.steps[a-1].testInstructionText&&this.state.steps[a-1].testInstructionText?!0:!1},moveHotspot:function(){var a=this.getCurrentStepObj();if(a){var b=this.getHotspotForStep(this.state.overallStep),
c=this;this.$elements.hotspot.css({top:b.top+"px",left:b.left+"px",width:b.width+"px",height:b.height+"px"});this.getEventTypeForStep(this.state.overallStep)==tryMe.CAPTURE_EVENT.TYPED&&this.moveTypedHotspot(b);if(a.secondaryHotspotEls){var d=this.getCarouselItemForStep(this.state.overallStep);a.secondaryHotspotEls.each(function(b,f){b=c.getHotspotScaledPositionAndDims(a.secondaryHotSpots[b],d,c.getScale());$(this).css(b)})}}},moveTypedHotspot:function(a){0>a.width&&this.getCurrentStepObj().hideInput();
$(tryMe.Typed.inputSelector,this.$container).css({width:a.width+"px",height:a.height+"px"})},tryNext:function(a,b){return{then:function(b,d){a?b():d()}}},getCurrentStep:function(){return this.getCurrentStepFromOverallStep(this.state.overallStep)},getPreviousStep:function(){var a=this.getCurrentStep(),b=a-1;return 1<a&&void 0!=this.getStepObjById(b)?b:-1},getCurrentStepObj:function(){return 0==this.state.overallStep?!1:this.getStepObjById(this.state.overallStep)},getNextStep:function(){return this.state.overallStep+
1},getNextStepObj:function(){return this.getStepObjById(this.getNextStep())},getStepObjById:function(a){return this.state.steps[a-1]},getCurrentSection:function(){return this.getCurrentSectionFromOverallStep(this.state.overallStep)},getNumberOfSections:function(){return this.options.sections.length},isEndOfSection:function(){var a=this.getCurrentSectionFromOverallStep(this.state.overallStep),b=this.getStepObjById(this.state.overallStep+1);return this.getOverallStepFromSectionAndStep(a+1,0)===this.state.overallStep||
this.state.overallStep===this.state.steps.length||b.eventType===tryMe.CAPTURE_EVENT.STOP},overallStepIsLastStep:function(a){return 0===this.getNextValidStep(a)},hideHintText:function(){this.$elements.hotspot.hasClass("tooltipstered")&&this.$elements.hotspot.tooltipster("destroy")},addFontInfoTo:function(a,b){null!=b&&b.useCustomTheme&&(null!=b.backgroundColor&&a.css({"background-color":this.getColorFromJavaColorString(b.backgroundColor)}),null!=b.textFillColor&&a.css({color:this.getColorFromJavaColorString(b.textFillColor)}),
null!=b.fontSize&&a.css({"font-size":this.getFontSizeFromJavaFontSize(b.fontSize)}),null!=b.fontType&&a.css({"font-family":b.fontType}))},getColorFromJavaColorString:function(a){return"#"+a.substring(a.indexOf("x")+1)},getFontSizeFromJavaFontSize:function(a){return a.split(" ").join("")},toggleRestartAnimation:function(a,b){this.$elements.infoScreen.find(".info-text").html(b||this.getCurrentStepObj().instructionalText);this.$elements.infoScreen.removeClass("modal-faded");this.$elements.infoScreen.find(".centered-element").show();
this.$elements.infoScreen.find(".info-restart").show();this.$elements.infoScreen.fadeIn(this.options.FADE_TIME).prop("disable",!1);a||setTimeout($.proxy(function(){this.closeInfoScreen()},this),this.options.FADE_TIME*this.options.FADE_MULTIPLIER)},closeInfoScreen:function(){this.$elements&&(this.$elements.infoScreen.addClass("modal-faded"),this.$elements.infoScreen.fadeOut(this.options.FADE_TIME))},toggleContinueModal:function(){this.$elements.infoScreen.find(".info-restart").hide();this.$elements.continueScreen.fadeIn(this.options.FADE_TIME).prop("disable",
!1)},isEndOfPath:function(){var a=this.options.sections[this.getCurrentSection()-1];if(!this.state.started)return!1;var b;"undefined"!=typeof branchData&&(b=branchData);return"SECTION"!=a.sectionType&&this.getCurrentStep()==a.numberOfSteps&&!this.state.switchingSections||"SECTION"==a.sectionType&&this.getCurrentStep()==a.numberOfSteps&&!this.getSideContainerManager(this).hasNextViableStepFromStepNumWithPath(this.state.overallStep-1,b)?!0:!1},doBeforeEnd:function(a){a()},updateList:function(a,b){var c=
this.getCurrentStepFromOverallStep(this.state.overallStep),d=this.getCurrentSectionFromOverallStep(this.state.overallStep),e=this,f=this.getCurrentStepObj(),g=f?f.hasHotspot():!1;this.state.prevEventType=this.state.currentEventType;f&&(this.state.currentEventType=f.eventType);this.$elements.sideContainer.find(".list-group .list-group-item").each(function(){var b=$(this).data("step-count"),f=$(this).data("section-count");f<d||f==d&&b<c||(f==d&&b==c?($(this).children(".try-me-done-overlay").hide(),
(!g&&e.state.overallStep<e.state.steps.length||!g&&e.state.overallStep<=e.state.steps.length&&e.state.currentEventType!=tryMe.CAPTURE_EVENT.STOP&&e.state.currentEventType!=tryMe.CAPTURE_EVENT.DECISION)&&$(this).find(".continue-container").removeClass("hidden")):(e.isEndOfPath()||($(this).removeClass("active"),$(this).addClass("disabled")),$(this).children(".try-me-done-overlay").hide(),e.state.overallStep==e.state.steps.length&&e.toggleItemCircle($(this),"checkmark"),a&&a($(this))))});if(e.getSideContainerManager(e).hasNextViableStepFromStepNumWithPath(e.state.overallStep-
1,b))e.$elements.infoScreen.prop("disabled")||this.$elements.infoScreen.prop("disabled",!0).fadeOut(this.options.FADE_TIME);else if(e.isEndOfPath()&&(e.getSideContainerManager(e).getStep(e.state.overallStep-1).stepEventType===tryMe.CAPTURE_EVENT.STOP&&e.getSideContainerManager(e).getStep(e.state.overallStep-1).hideContinueButton(),"DECISION"!=e.getCurrentStepObj().eventType))$(f).one(tryMe.EVENT.STEP_FINISHED,$.proxy(function(){("undefined"===typeof testMe||this.inReview&&this instanceof testMe)&&
this.$container.trigger(tryMe.EVENT.COMPLETE);this.doBeforeEnd(function(){e.toggleRestartAnimation(!1,f.getRestartText())})},this));0==this.state.overallStep||0==this.$elements.infoScreen.prop("disabled")?(this.$elements.hotspot.css("visibility","hidden"),this.$elements.hintButton.hide()):this.state.currentEventType==tryMe.CAPTURE_EVENT.TYPED?(this.$elements.hotspot.css("visibility","hidden"),this.toggleTypingTooltip(!0),null!=this.getCurrentStepObj().stringTyped&&this.$elements.hotspot.css("visibility",
""),this.$elements.hintButton.prop("disabled",!1),this.$elements.hintButton.show()):(this.$elements.hotspot.css("visibility",""),this.toggleTypingTooltip(!1),this.$elements.hintButton.show(),this.$elements.hintButton.prop("disabled",!1));this.$elements.hotspot.removeClass("hotspotHint")},toggleItemCircle:function(a,b){a.find(".step-checkmark, .step-number").hide().filter(".step-"+b).show()},showTooltip:function(a,b){b=b||{};if(b.content){a.hasClass("tooltipstered")&&a.tooltipster("destroy");var c=
this.getToolTipPosition(a),d=0,e=!0,f=this,g=b.functionReady||function(){};delete b.functionReady;var h=b.functionAfter||function(){};delete b.functionAfter;"right"===c&&(d=this.$elements.carouselContainer.height()/2,e=!1);b=$.extend({content:"",position:c,maxWidth:Math.max(this.$elements.carousel.width()/2,250),functionPosition:function(a,b,c){c.coord.top/=f.getScale(!0);c.coord.left/=f.getScale(!0);c.size.height/=f.getScale(!0);c.size.width/=f.getScale(!0);c.target/=f.getScale(!0);f.state.fullscreen&&
("top"==c.side||"bottom"==c.side?c.coord.left+=(b.geo.origin.offset.left-c.coord.left)/2:c.coord.top+=(b.geo.origin.offset.top-c.coord.top)/2);c.coord.top+=d;a=$(b.tooltip).find("img").get();for(var e=0;e<a.length;e++){var g=a[e];$(g).on("load",function(){g.naturalWidth>b.geo.available.document.right.width&&$(g).css("max-width",""+(b.geo.available.document.right.width-b.geo.available.document.right.width/100*5)+"px")})}return c},functionReady:function(a,b){f.openTooltip=$(b.tooltip);f.doTooltipForFullScreen();
g.call(this,a,b)},functionAfter:function(a){f.openTooltip=null;h.call(this,a)},trigger:"hover",arrow:e,interactive:!0,theme:this.options.TOOLTIP_THEME},b);var c={"overflow-y":"auto","word-break":"break-word","max-height":Math.max(this.$elements.carousel.height()/2,250)+"px"},e=!0,k,l;try{l=$(b.content)}catch(m){e=!1}e&&(k=l.find(".content"),e=k[0]?!0:!1);e?(k.css(c),b.content=l):b.content=$("\x3cdiv\x3e",{css:c}).append(b.content);b.content.find("h4").css("max-width",Math.max(this.$elements.carousel.width()/
2,250)+"px");a.tooltipster(b).tooltipster("show")}},showHintText:function(a){this.getHintTextForStep(a)&&this.showTooltip(this.$elements.hotspot,{content:this.getHintTextForStep(a)})},getToolTipPosition:function(a){a=this.$elements.hotspot.position();a.height=this.$elements.hotspot.height();a.width=this.$elements.hotspot.width();return 0>a.width?"right":(a.top+(a.top+a.height))/2>this.$elements.carouselContainer.height()/2?"top":"bottom"},getHintTextForStep:function(a){var b=this.state.steps[a-1].hintText;
this.getEventTypeForStep(a)!=tryMe.CAPTURE_EVENT.TYPED||b||(b=this.state.steps[a-1].instructionalText);return b},showTypedTextHint:function(a){a.currentStepValidated||($(tryMe.Typed.inputSelector,this.$container).val(""),$(tryMe.Typed.inputSelector,this.$container).trigger("focus"));$(tryMe.Typed.inputSelector,this.$container).addClass("inputHotSpotHint");var b=this;setTimeout(function(){$(tryMe.Typed.inputSelector,b.$container).removeClass("inputHotSpotHint")},4E3)},toggleTypingTooltip:function(a){if(a){var b=
this;null==this.getCurrentStepObj().stringTyped?(this.$elements.hotspot.attr("data-original-title","\x3cp\x3e"+this.getCurrentStepObj().instructionalText+"\x3c/p\x3e"+this.$elements.tooltipTemplate.prop("innerHTML")).tooltip({html:!0,trigger:"manual",container:this.$elements.carousel,placement:"auto bottom"}).tooltip("show"),this.$elements.carousel.find(".tooltip .btn-continue").on("click",function(){b.nextStep()})):$(tryMe.Typed.inputSelector,this.$container).trigger("focus")}else this.$elements.hotspot.tooltip("hide"),
this.$elements.carousel.find(".tooltip .btn-continue").off()},scrollToStep:function(){var a=this.$elements.sideContainer.find(this.sideContainerScrollParentSelector),b=this.$elements.sideContainer.find(".active"),b="auto"===a.css("overflow-y")?{scrollTop:(b[0]?b.position().top/this.options.transformScale:0)-a.position().top+a.scrollTop()}:{scrollLeft:(b[0]?b.position().left:0)-a.position().left+a.scrollLeft()};a.stop();a.animate(b)},toggleRestartButton:function(){$restartBTN=this.$elements.carouselContainer.find(".try-me-restart-btn");
this.state.restartButtonEnabled?$restartBTN.removeClass("disabled"):$restartBTN.addClass("disabled")},toggleHintButton:function(){$hintButton=this.$elements.hintButton;this.state.hintButtonEnabled?$hintButton.removeClass("disabled"):$hintButton.addClass("disabled")},resizeSideContainer:function(){this.$elements.sideContainer.find(".panel").css("max-height",this.$elements.carouselContainer.height()+"px");this.moveHotspot()},positionDragOverlay:function(a,b){this.getScale();b=this.getHotspotForStep(b||
this.state.overallStep);this.$elements.dragOverlay.width(b.width);this.$elements.dragOverlay.height(b.height);a?(this.$elements.dragOverlay.css("left",a.pageX-this.$elements.carousel.offset().left-b.width/2),this.$elements.dragOverlay.css("top",a.pageY-this.$elements.carousel.offset().top-b.height/2)):(this.$elements.dragOverlay.css("left",b.left),this.$elements.dragOverlay.css("top",b.top))},resetDrag:function(a,b){this.state.dragging=!1;if(a)this.$elements.dragOverlay.fadeOut("fast");else this.$elements.dragOverlay[b?
"css":"animate"]({top:this.$elements.hotspot.css("top"),left:this.$elements.hotspot.css("left"),opacity:0})},setFullScreenModeClasses:function(a){var b=dkiUA.isIE();a?(this.$elements.carouselContainer.addClass("capture-fullscreen-height"),this.$container.addClass("capture-fullscreen-overflow"),b&&this.$container.addClass("IE-media-screen-no-margin")):(this.$elements.carouselContainer.removeClass("capture-fullscreen-height"),this.$container.removeClass("capture-fullscreen-overflow"),this.$container.removeClass("IE-media-screen-no-margin"))},
adjustImageSizes:function(a){a?$(".capture-image").css("max-height",screen.availHeight-$(".row.controls").height()-parseInt($(".bottom-buffer").css("margin-top").split("px")[0],10)):$(".capture-image").css("max-height","")},getScale:function(a){var b=this.getOverallStep?this.getOverallStep()-1:0;if(this.state.fullscreen!=captureProjectUtils.getfullscreenMode()){var c=captureProjectUtils.getfullscreenMode();this.setFullScreenModeClasses(c);this.state.fullscreen=c;this.doTooltipForFullScreen()}return captureProjectUtils.getScale(this.$elements,
this.state.fullscreen,b,a)},xyInElement:function(a,b,c){c=c[0].getBoundingClientRect();return c.left<=a&&a<=c.right&&c.top+window.scrollY<=b&&b<=c.bottom+window.scrollY?!0:!1},isShowByDefaultSection:function(a){return tryMe.CONST.SECTION_TYPES[this.options.sections[a-1].sectionType].showByDefault},canNavigateToSection:function(a){return a<=this.options.sections.length?this.getCurrentSectionFromOverallStep(this.state.overallStep)===a?!0:this.isShowByDefaultSection(a):!1},getOverallStep:function(){return this.state.overallStep},
getNextValidStep:function(){for(var a=this.state.overallStep+1,b=this.getCurrentSectionFromOverallStep(a);a<=this.state.steps.length&&!this.canNavigateToSection(b)&&b<this.options.sections.length;)b+=1,a=this.getOverallStepFromSectionAndStep(b,1);return b>this.options.sections.length?0:a},goToStep:function(a,b){this.$elements.sideContainer.find(".list-group");var c=$(a).closest("li").attr("data-step-count");a=$(a).closest("li").attr("data-section-count");c=parseInt(c,10);a=parseInt(a,10);c=this.getOverallStepFromSectionAndStep(a,
c);if(b&&this.inReview){this.assessment.reviewState.stepsAlreadyReviewed=[];this.hideHintText();for(b=1;b<=c;){for(a=0;a<this.assessment.reviewState.stepsToGoThrough.length;a++)if(b==this.assessment.reviewState.stepsToGoThrough[a].stepIdx){this.assessment.reviewState.stepsAlreadyReviewed.push(this.assessment.reviewState.stepsToGoThrough[a].stepIdx);break}b++}this.assessment.reviewState.currentReviewStepIndex=this.assessment.reviewState.stepsAlreadyReviewed.length;this.assessment.reviewState.userManuallySwitchingSteps=
!0}~this.state.completedSteps.indexOf(c)&&c<=this.state.steps.length&&(b=this.getCurrentSectionFromOverallStep(this.state.overallStep),a=this.getCurrentSectionFromOverallStep(c),b!=a&&(this.state.secondaryPathReturns=[]),this.doStepChange(c,function(){this.state.overallStep==this.state.steps.length-1&&this.$elements.continueScreen.find(".info-continue").show()}))},nextStep:function(a,b){a=null;var c=this.isEndOfPath(),d=!this.getSideContainerManager(this).hasNextViableStepFromStepNumWithPath(this.state.overallStep-
1,b);0<this.state.secondaryPathReturns.length&&c&&(a=this.state.secondaryPathReturns.pop());c&&!b&&this.state.started&&(d||null!=a&&!a.isValid()||null==a&&(this.options.sections[this.getCurrentSection()-1].sectionType==tryMe.CAPTURE_EVENT.ALTERNATIVE_PATH||this.options.sections[this.getCurrentSection()-1].sectionType==tryMe.CAPTURE_EVENT.BRANCH))?(this.state.completedSteps.push(this.state.overallStep),this.updateList()):(d=this.getNextValidStep(),b&&(b.stepToReturnTo=b.stepToReturnTo||d,d=this.getOverallStepFromSectionAndStep(b.sectionToJumpTo,
1),this.afterSection=$.proxy(function(){this.afterSection=null;return b.stepToReturnTo},this)),c&&null!=a&&a.isValid()&&(d=this.getOverallStepFromSectionAndStep(a.getX(),a.getY())),this.state.hintButtonEnabled=!0,this.toggleHintButton(),this.doStepChange(d,function(){this.state.overallStep!=this.state.steps.length-1&&this.$elements.continueScreen.find(".info-continue").show();0>this.state.completedSteps.indexOf(this.state.overallStep)&&0!=this.state.overallStep&&this.state.completedSteps.push(this.state.overallStep);
if(0==this.state.overAllStep)this.onEndReached()},this.state.currentEventType===tryMe.CAPTURE_EVENT.DRAG_FINISH,"undefined"!=typeof b,b))},prevStep:function(){this.state.currentEventType!==tryMe.CAPTURE_EVENT.DRAG_FINISH?this.doStepChange(this.state.overallStep-1,void 0,!1):this.doStepChange(this.state.overallStep-1)},getNextStep:function(){return this.state.overallStep+1},doStepChange:function(a,b,c,d,e){this.hideHintText();d&&(this.state.switchingSections=!0);d=this.getCurrentSectionFromOverallStep(a);
var f=this.getCurrentSectionFromOverallStep(this.state.overallStep);d!=f&&!this.isShowByDefaultSection(f)&&"BRANCH"==!this.options.sections[this.getCurrentSectionFromOverallStep(a)-1].sectionType&&this.isEndOfSection();d=this.state.overallStep-1;var f=0===this.state.overallStep,g=this.getCurrentStepObj(),h=this.getStepObjById(a);this.$elements.sideContainer.find(".list-group .continue-container").addClass("hidden");this.$elements.sideContainer.find(".active .arrow-hint.arrow-hint-active").removeClass("arrow-hint-active");
g&&g.finish();h&&(this.$elements.startScreen.fadeOut(this.options.FADE_TIME).find("button").prop("disabled",!0),this.$elements.carousel.carousel(Math.max(0,a-1)),this.state.overallStep=a);this.moveHotspot();if(f||this.state.currentEventType!==tryMe.CAPTURE_EVENT.DRAG_FINISH||!this.state.dragging||this.state.currentEventType===tryMe.CAPTURE_EVENT.DRAG_FINISH&&c)0<=d&&this.getSideContainerManager(this).setStepAsPlayedFromOverallStep(d,!0),this.getSideContainerManager(this).setStepAsActiveFromOverallStep(this.state.overallStep-
1),this.updateList(!1,e);this.scrollToStep();if(h){var k=this;h.onInteraction(function(a,b,c){var d=this;k.tryNext(a,b).then(function(){k.doStepWillContiueAction(d,c)},function(){k.doStepNoContinueAction(d)})}).start()}b&&b.apply(this);a={y:this.getCurrentStep(),x:this.getCurrentSection()};this.$container.trigger(tryMe.EVENT.STEP_CHANGED,a);this.state.switchingSections=!1;this.state.restartButtonEnabled=1<this.state.overallStep;this.state.hintButtonEnabled=!0;this.toggleRestartButton();this.toggleHintButton()},
doStepWillContiueAction:function(a,b){if(a.onContinueAction)this[a.onContinueAction](a,b);a.onContinue()},doStepNoContinueAction:function(a){if(a.noContinueAction)this[a.noContinueAction](a);a.onNoContinue()},onEndReached:function(){this.$elements.startScreen.fadeIn(this.options.FADE_TIME).find("button").prop("disabled",!1)},flashTypedStepHint:function(){var a=this.$elements.sideContainer.find(".active");a.addClass("stepHint");setTimeout(function(){a.removeClass("stepHint")},400)},flashHint:function(a){var b=
this.$elements.sideContainer.find(".active");a&&this.$elements.hintButton.addClass("stepHint");b.addClass("stepHint");setTimeout($.proxy(function(){this.$elements.hintButton.removeClass("stepHint");b.removeClass("stepHint")},this),400)},flashContinue:function(){this.$elements.sideContainer.find(".active .arrow-hint").addClass("arrow-hint-active")},showTypedStepHint:function(a){this.showTypedTextHint(a)},showHint:function(a,b){a=a||this.state.overallStep;if(stepObj=this.state.steps[a-1]){this.$elements.hintButton.prop("disabled",
!0);var c=this.getEventTypeForStep(a+1);if(stepObj.eventType==tryMe.CAPTURE_EVENT.DRAG_START&&c==tryMe.CAPTURE_EVENT.DRAG_FINISH)this.getScale(),c=this.getHotspotForStep(a+1),this.positionDragOverlay(null,a),this.$elements.dragOverlay.show(),this.$elements.dragOverlay.css("opacity",1),this.$elements.dragOverlay.stop(),this.$elements.dragOverlay.animate({left:c.left+c.width/2-this.$elements.hotspot.width()/2+"px",top:c.top+c.height/2-this.$elements.hotspot.height()/2+"px"},1E3,$.proxy(function(){this.$elements.dragOverlay.fadeOut("fast");
this.$elements.hintButton.prop("disabled",!1)},this));else if(stepObj.eventType==tryMe.CAPTURE_EVENT.TYPED)this.showTypedStepHint(stepObj);else if(0<this.$elements.hotspot.height()){if(this.$elements.hotspot.addClass("hotspotHint"),stepObj.secondaryHotspotEls&&0<stepObj.secondaryHotspotEls.length)for(c=0;c<stepObj.secondaryHotspotEls.length;c++)stepObj.secondaryHotSpots[c].hotSpotResult===tryMe.CAPTURE_EVENT.NEXT_STEP&&stepObj.secondaryHotspotEls[c].classList.add("hotspotHint")}else this.flashContinue();
b||this.showHintText(a);this.$container.trigger(tryMe.EVENT.HINT,this)}},toggleFullscreen:function(){this.state.FullscreenTransition=!0;captureProjectUtils.toggleFullscreen(this.$container,this.$elements,this.getScale(),$.proxy(function(a){this.state.fullscreen=a;this.state.tooltipsRepositioned=!1;this.setFullScreenModeClasses(this.state.fullscreen);this.state.FullscreenTransition=!1;this.doTooltipForFullScreen();this.adjustImageSizes(this.state.fullscreen)},this))},doTooltipForFullScreen:function(){if(this.openTooltip&&
!this.state.FullscreenTransition){var a=this,b=a.openTooltip.find(".content").scrollTop();a.state.fullscreen?(a.repositionTooltipsters(),$(".tooltipstered").each(function(){$($(this).tooltipster("instance").elementTooltip()).appendTo(a.$container);$($(this).tooltipster("instance").elementTooltip()).find(".content").scrollTop(b)})):(a.scrollToStep(),a.repositionTooltipsters(),a.openTooltip.appendTo($("body")),a.openTooltip.find(".content").scrollTop(b))}},repositionTooltipsters:function(){this.state.tooltipsRepositioned||
($(".tooltipstered").each(function(){$(this).tooltipster("instance").reposition()}),this.state.tooltipsRepositioned=!0)},destroy:function(){$(window).off("resize."+this.$container.attr("id"));this.$elements.carousel.off();this.$elements.hotspot.off();this.$elements.carousel.off();this.$elements.carousel.find("img").off();this.$elements.startScreen.find(".btn").off();this.$elements.continueScreen.find(".btn").off();this.$elements.hintButton.off();this.$elements=null;clearInterval(this.state.resizeInterval);
clearInterval(this.state.assessTimer)},getStepFactory:function(){this.stepFactory||(this.stepFactory=new tryMe.StepFactory);return this.stepFactory},getpanelManager:function(a){this.panelManager||(this.panelManager=new tryMe.panelManager(this));return this.panelManager},getSideContainerManager:function(a){this.sideContainerManager||(this.sideContainerManager=new tryMe.sideContainerManager(this,null,null),this.sideContainerManager.init());return this.sideContainerManager}};tryMe.StepFactory=function(){};
tryMe.StepFactory.prototype={getClassPath:function(a){switch(a.eventType){case tryMe.CAPTURE_EVENT.DRAG_START:a="DragStart";break;case tryMe.CAPTURE_EVENT.DRAG_FINISH:a="DragFinish";break;case tryMe.CAPTURE_EVENT.KEY_COMBO:case tryMe.CAPTURE_EVENT.SPECIAL_KEY:a="Step";break;case tryMe.CAPTURE_EVENT.TYPED:a="Typed";break;case tryMe.CAPTURE_EVENT.DECISION:a="Decision";break;case tryMe.CAPTURE_EVENT.SELECT:a="Select";break;case tryMe.CAPTURE_EVENT.STOP:a="StopCapture";break;default:a="ClickStep"}return a},
createStep:function(a,b,c){var d=this.getClassPath(a),d=this.findClass(d);d||(d=tryMe.Step);return new d(a,b,c)},findClass:function(a){return tryMe[a]}};
var TwoDimensionalPosition=function(){this.y=this.x=-1;this.set=function(a,b){this.x=a;this.y=b};this.reset=function(){this.set(-1,-1)};this.isValid=function(){return-1!==this.x&&-1!==this.y};this.getX=function(){return this.x};this.getY=function(){return this.y}},ContainerStep=function(a,b,c,d){this.stepID=b;this.stepNum=0;this.element=a;this.played=!1;this.player=c;this.showing=d;this.isShowingContinueButton=!1;this.stepObj=this.stepEventType=null;this.setStepNum=function(a){this.stepNum=a};this.showStep=
function(){this.showing||($(a).addClass("showForAlternate"),this.showing=!0)};this.hideStep=function(){this.showing&&($(a).removeClass("showForAlternate showByDefault"),this.showing=!1)};this.stepPlayed=function(b){b&&(this.played=!0,this.player.toggleItemCircle($(a),"checkmark"),$(a).removeClass("active"),$(a).find(".continue-container").addClass("hidden"),$(a).addClass("disabled"))};this.activateStep=function(){$(a).addClass("active");$(a).removeClass("disabled");this.player.toggleItemCircle($(a),
"number")};this.resetStep=function(b){b&&(this.showing=!1);$(a).addClass("disabled");$(a).removeClass("active");$(a).removeClass("showForAlternate");this.stepSetup()};this.stepSetup=function(){this.player.toggleItemCircle($(a),"number",!0);this.stepObj=this.player.getStepObjById(this.stepID+1);this.stepEventType=this.player.getStepObjById(this.stepID+1).eventType};this.showContinueButton=function(){$(a).find(".continue-container").removeClass("hidden");this.isShowingContinueButton=!0};this.hideContinueButton=
function(){$(a).find(".continue-container").hide();this.isShowingContinueButton=!1};this.getStepId=function(){return this.stepID};this.setStepUiNum=function(b){$(a).find(".col-step .step-number").html(b)};this.getStepUiNum=function(){return $(a).find(".col-step .step-number").html()}},ContainerSection=function(a,b,c,d,e,f){this.sectionId=b;this.elements=a;this.sectionTitleElement=c;this.shownStepTypes=d;this.steps=[];this.player=f;this.maxStepNum=this.minStepNum=e;this.isHiddenSection=this.defaultHidden=
!0;this.sectionIntroduction=this.sectionType=null;this.hasShownIntroduction=!1;this.initializeSection=function(){var b,c=0,d=this.minStepNum;for(b=0;b<this.elements.length;b++){var e=new ContainerStep(a[b],d++,f);$(a[b]).hasClass(".showByDefault")&&(this.defaultHidden=this.isHiddenSection=!1);e.setStepNum(c++);e.stepSetup();this.steps.push(e)}this.defaultHidden||this.hideSection();this.maxStepNum=d-1;this.sectionType=this.player.options.sections[this.sectionId-1].sectionType;if(b=this.player.$elements.sectionInfo.find("#section-"+
this.getSectionId()).data("section-introduction"))this.sectionIntroduction=b;return d};this.showSection=function(){$.each(this.steps,function(a,b){b.showStep()});$(this.sectionTitleElement).addClass("showForAlternate");this.isHiddenSection=!1};this.resetSection=function(){var a=this;$.each(this.steps,function(b,c){c.resetStep(a.defaultHidden)});this.defaultHidden&&($(this.sectionTitleElement).removeClass("showForAlternate"),this.isHiddenSection=!0);this.hasShownIntroduction=!1};this.hideSection=function(){this.defaultHidden&&
($.each(this.steps,function(a,b){b.hideStep()}),$(this.sectionTitleElement).removeClass("showForAlternate showByDefault"),this.isHiddenSection=!0)};this.getSectionIntroduction=function(a){this.hasShownIntroduction=!0;return this.sectionIntroduction};this.checkIntroductionShown=function(){return this.sectionIntroduction?this.hasShownIntroduction:!0};this.getSectionSize=function(){return this.steps.length};this.getSectionId=function(){return this.sectionId};this.hasStepNum=function(a){return a>=this.minStepNum&&
a<=this.maxStepNum};this.getStep=function(a){return this.steps[a]};this.setStepUiNums=function(a){var b=1;$.each(this.steps,function(c,d){a(d)&&d.setStepUiNum(b++)})}};
tryMe.sideContainerManager=function(a,b,c){this.shownStepTypes=b;this.player=a;this.mode=c;this.sections=[];this.fetchOverallStepFromSectionAndStep=function(a,b){return this.sections[a-1].getStep(b-1).stepID+1};this.getSideContainerSectionForStep=function(a){var b=null;$.each(this.sections,function(c,g){g.hasStepNum(a)&&null==b&&(b=g)});return b};this.getStep=function(a,b){var c=this.getSideContainerSectionForStep(a);return c?(a=c.getStep(a-c.minStepNum),c.isHiddenSection&&!b&&c.showSection(),a):
null};this.setStepAsPlayedFromOverallStep=function(a,b){this.getStep(a).stepPlayed(b)};this.setStepAsActiveFromOverallStep=function(a){this.getStep(a).activateStep()};this.reset=function(){$.each(this.sections,function(a,b){b.resetSection()})};this.hasNextViableStepFromStepNumWithPath=function(a,b){var c=b=!1;0<this.player.state.secondaryPathReturns.length&&(this.player.state.secondaryPathReturns[this.player.state.secondaryPathReturns.length-1].isValid()?b=!0:c=!0);this.hasNextViableStepFromStepNum(a,
c)&&(b=!0);return b};this.hasNextViableStepFromStepNum=function(a,b){0>a&&(a=0);var c=this.getSideContainerSectionForStep(a),g=!1;if(!b&&"BRANCH"!=c.sectionType)for(b=c.sectionId;b<this.player.options.sections.length;b++){var h=this.player.options.sections[b];h&&"SECTION"==h.sectionType&&(g=!0)}c&&this.sectionHasValidStepsAfterStepNum(a)&&(g=!0);return g};this.sectionHasValidStepsAfterStepNum=function(a){var b=this.getSideContainerSectionForStep(a);this.getStep(a,!0);return b.maxStepNum>a?!0:!1};
this.sideContainerSectionFilter=function(a){return a.classList.contains("sectionHeader")};this.getLastStepIdInSection=function(a){a=this.sections[a];return a.steps[a.steps.length-1].stepID}};
tryMe.sideContainerManager.prototype={init:function(){var a=this.player.$elements.sideContainer.find(".list-group").children(),b=[],c=null,d=this,e=1,f=0;$.each(a,function(a,h){d.sideContainerSectionFilter(this)?0!=b.length&&(a=new ContainerSection(b,e++,c,null,f,d.player),f=a.initializeSection(),d.sections.push(a),c=this,b=[]):b.push(this)});0!=b.length&&(a=new ContainerSection(b,e++,c,null,f,this.player),a.initializeSection(),d.sections.push(a))}};
tryMe.panelManager=function(a){this.currentPanels=Array(3);this.currentPanels[0]=[];this.currentPanels[1]=[];this.currentPanels[2]=[];this.currentActivePanel=new TwoDimensionalPosition;this.player=a;this.panelOverlay=this.player.$elements.GenericPanelOverlay;this.panelContentContainer=this.player.$elements.GenericPanelContentContainer;this.showPanel=function(){this.panelOverlay.removeClass("hide-general-panel")};this.hidePanel=function(){this.panelOverlay.addClass("hide-general-panel")};this.addPanelToQue=
function(a,c){this.currentPanels[c].push(a)};this.addContentToPanel=function(a){this.clearContentFromPanel();a=a.clone(!0);this.panelContentContainer.append(a)};this.clearContentFromPanel=function(){this.panelContentContainer.empty()};this.displayPanels=function(){0<this.currentPanels[0].length?(this.currentActivePanel.set(0,0),this.addContentToPanel(this.currentPanels[0][0]),this.showPanel()):0<this.currentPanels[1].length?(this.currentActivePanel.set(1,0),this.addContentToPanel(this.currentPanels[1][0]),
this.showPanel()):0<this.currentPanels[2].length&&(this.currentActivePanel.set(2,0),this.addContentToPanel(this.currentPanels[2][0]),this.showPanel())};this.addAndDisplayPanel=function(a,c,d){switch(c){case tryMe.CONST.PANEL_TYPES.BASIC:this.addPanelToQue(a,tryMe.CONST.PANEL_TYPES.BASIC.priority);this.displayPanels();break;case tryMe.CONST.PANEL_TYPES.WITH_CALLBACK:this.addPanelToQue(a,tryMe.CONST.PANEL_TYPES.WITH_CALLBACK.priority);this.displayPanels();break;case tryMe.CONST.PANEL_TYPES.FROM_STEP:this.addPanelToQue(a,
tryMe.CONST.PANEL_TYPES.FROM_STEP.priority),this.displayPanels()}};this.deleteActivePanel=function(){this.currentActivePanel.isValid()&&(this.currentPanels[this.currentActivePanel.getX()].splice(this.currentActivePanel.getY()),this.currentActivePanel.reset());this.displayPanels()};this.closePanel=function(){this.hidePanel();this.deleteActivePanel()}};
tryMe.Step=function(a,b,c){this.id=c;this.player=b;this.interactionHandler=function(){};this.subscribedElements=[];var d=this;$.each(a,function(b,c){d[b]=a[b]});return this};tryMe.Step.continueButtonSelector=".info-continue .btn-step-continue";
tryMe.Step.prototype={onContinueAction:"nextStep",setupAdditionalHotspot:function(){if(0<this.secondaryHotSpots.length){for(var a=this,b=0;b<this.secondaryHotSpots.length;b++){var c=this.secondaryHotSpots[b],d=$('\x3cdiv class\x3d"targetHotspot secondary"data-sectionToJumpTo\x3d"'+c.sectionToJumpTo+'"data-id\x3d"'+b+'"'+(c.stepToReturnTo?' data-stepToReturnTo\x3d"'+c.stepToReturnTo+'"':"")+"\x3e\x3cdiv\x3e").appendTo(this.player.$elements.carousel.find(".carousel-inner"));this.secondaryHotspotEls=
this.secondaryHotspotEls?this.secondaryHotspotEls.add(d):d;var e=new TwoDimensionalPosition;e.set(c.sectionToJumpTo+1,1);d.on("click",e,function(b){var d=b.data,e=new TwoDimensionalPosition;e.set(-1,-1);c.hotSpotResult==tryMe.CAPTURE_EVENT.NEXT_STEP?a.interacted(!0,b):c.hotSpotResult==tryMe.CAPTURE_EVENT.BRANCH?(a.player.state.secondaryPathReturns.push(e),a.interacted(!0,b,{sectionToJumpTo:d.getX(),stepToReturnTo:d.getY()})):c.hotSpotResult==tryMe.CAPTURE_EVENT.ALTERNATIVE_PATH&&(e.set(a.player.getCurrentSectionFromOverallStep(a.player.state.overallStep),
c.stepToReturnTo),a.player.state.secondaryPathReturns.push(e),a.interacted(!0,b,{sectionToJumpTo:d.getX(),stepToReturnTo:d.getY()}))});this.addKeyEventsForHotspot(c)}this.player.moveHotspot()}},removeAdditionalHotspots:function(){this.secondaryHotspotEls&&(this.secondaryHotspotEls.each(function(){$(this).hasClass("tooltipstered")&&$(this).tooltipster("destroy")}),this.secondaryHotspotEls.remove(),delete this.secondaryHotspotEls)},start:function(){this.bindHandlers();this.hasHotspot()?this.addKeyEventsForHotspot(this.hotSpot):
this.setupNoHotspot();this.setupAdditionalHotspot();this.player.$container[0].focus();return this},finish:function(){this.removeHandlers();this.removeAdditionalHotspots();return this},onInteraction:function(a){this.interactionHandler=a;return this},isPaused:function(){return this.player.state.isPaused?!0:!1},interacted:function(a,b,c){return this.interactionHandler.call(this,a,b,c)},subscribe:function(a,b,c){a=a.split(" ").map(function(a){return a+".stepEvent"}).join(" ");if(b)this.player.$elements.carousel.on(a,
b,c);else this.player.$elements.carousel.on(a,c);~this.subscribedElements.indexOf(this.player.$elements.carousel)||this.subscribedElements.push(this.player.$elements.carousel)},removeHandlers:function(){for(var a=this.subscribedElements.length-1;0<=a;a--)this.subscribedElements[a].off(".stepEvent"),this.subscribedElements.pop()},hasHotspot:function(){return 0<parseInt(this.hotSpot.width,10)&&0<parseInt(this.hotSpot.height,10)},setupNoHotspot:function(a){var b=this,c=this.player.$elements.sideContainer.find(".row.active");
a=c.find(tryMe.Step.continueButtonSelector);a.on("click.stepEvent",function(a){a.stopPropagation();c.find(".arrow-hint").removeClass("arrow-hint-active");b.interacted(!0,a)});~this.subscribedElements.indexOf(a)||this.subscribedElements.push(a)},getHotspotById:function(a){return this.secondaryHotspotEls&&void 0!==a?$(this.secondaryHotspotEls.get(a)):this.player.$elements.hotspot},addKeyEventsForHotspot:function(a){if(a.keyCombination){var b=this;this.player.$container.on("keydown.stepEvent",function(c){if(c.key.toLowerCase()===
a.keyCombination.keyPressed.toLowerCase()){for(var d=0;d<a.keyCombination.modifiers.length;d++)if(!1===c[a.keyCombination.modifiers[d]+"Key"])return b.interacted(!1,c),!1;var e;a.sectionToJumpTo&&(e={sectionToJumpTo:a.sectionToJumpTo},a.stepToReturnTo&&(e.stepToReturnTo=a.stepToReturnTo));b.interacted(!0,c,e);return!1}});~this.subscribedElements.indexOf(this.player.$container)||this.subscribedElements.push(this.player.$container)}},getRestartText:function(){return this.player.options.STRINGS.RESTART_TEXT},
onContinue:function(){$(this).trigger(tryMe.EVENT.STEP_FINISHED)},bindHandlers:function(){},onNoContinue:function(){},hotspotResized:function(){},discardResources:function(){this.finish()}};tryMe.ClickStep=function(){tryMe.Step.apply(this,arguments);this.clicks=0};
tryMe.ClickStep.prototype=$.extend(Object.create(tryMe.Step.prototype),{bindHandlers:function(){var a=this,b=function(a){$(a).off("contextmenu touchend mouseup")},c=function(b){a.validateClickEvent(b,function(c){a.interacted(!0,b)},function(c){a.clicks==parseInt(c,10)&&c||(a.player.flashHint(!a.player.$elements.hintButton.prop("disabled")),a.interacted(!1,b))})};this.subscribe("mousedown touchstart",".targetHotspot:not(.secondary)",function(a){b(this);dkiUA.isIE();$(this).one("contextmenu",function(){b(this);
c(a);return!1});$(this).one("mouseup touchend",function(e){b(this);c(a);return!1});return!1});this.subscribe("mouseup touchstart","",function(b,c){a.isPaused()||c||(a.player.flashHint(!a.player.$elements.hintButton.prop("disabled")),clearTimeout(a.clickTimer),a.clicks=0)})},validateClickEventImmediate:function(a,b,c){this.validateClickEvent(a,b,c,!0)},validateClickEvent:function(a,b,c,d){var e=this,f=function(){c(this.clickCount);e.clicks==parseInt(this.clickCount,10)&&this.clickCount||(e.clicks=
0)};this.convertToCaptureMouseButton(a).matches(this.mouseButton||0)?(a.preventDefault(),a.stopPropagation(),this.clicks++,this.clicks!==parseInt(this.clickCount,10)&&this.clickCount?((1<this.clicks&&1<parseInt(this.clickCount,10)||!this.clickCount)&&this.clearClickTimer(),d?f():this.clickTimer=setTimeout(f,1500)):(this.clicks=0,b(this.clickCount),null!==this.clickTimer&&this.clearClickTimer())):((1<this.clicks&&1<parseInt(this.clickCount,10)||!this.clickCount)&&clearTimeout(this.clickTimer),f())},
clearClickTimer:function(){this.clickTimer&&clearTimeout(this.clickTimer)},convertToCaptureMouseButton:function(a){var b=a.button||0,c=this;switch(b){case 0:b=[0,1];break;case 1:b=[3];break;default:b=[b]}return{matches:function(d){return~b.indexOf(d)||"touchstart"==a.type&&c.options.mobile}}},interacted:function(a,b,c){return this.interactionHandler.call(this,a,b,c)},finish:function(){tryMe.Step.prototype.finish.call(this);this.clearClickTimer()}});
tryMe.DragStart=function(){tryMe.Step.apply(this,arguments)};
tryMe.DragStart.prototype=$.extend(Object.create(tryMe.Step.prototype),{start:function(){tryMe.Step.prototype.start.call(this);this.player.$elements.dragOverlay.hide()},bindHandlers:function(){var a=this;this.subscribe("mousedown touchstart",".targetHotspot:not(.secondary)",function(b){a.event=b;a.interacted(!0,b);a.player.$elements.dragOverlay.stop();b.preventDefault()});this.subscribe("mousedown touchstart",this.player.$elements.carouselContainer,function(a){a.preventDefault()})},finish:function(){tryMe.Step.prototype.finish.call(this);
this.event&&this.player.getNextStepObj().eventType===tryMe.CAPTURE_EVENT.DRAG_FINISH&&(this.player.positionDragOverlay(this.event),this.player.$elements.dragOverlay.show(),this.player.$elements.dragOverlay.css("opacity",1))}});tryMe.DragFinish=function(){tryMe.Step.apply(this,arguments);this.pass=!1};
tryMe.DragFinish.prototype=$.extend(Object.create(tryMe.Step.prototype),{noContinueAction:"prevStep",start:function(){tryMe.Step.prototype.start.call(this);-1!=this.player.getPreviousStep()&&this.player.getStepObjById(this.player.getPreviousStep()).eventType!=tryMe.CAPTURE_EVENT.DRAG_START&&this.showDragProxy()},bindHandlers:function(){var a=this;this.subscribe("mousemove touchmove","",function(b){"touchmove"==b.type&&(b=b.originalEvent.touches[0]);a.player.positionDragOverlay(b)});this.subscribe("mousedown touchstart",
this.player.$elements.carouselContainer,function(a){a.preventDefault()});this.subscribe("mouseup touchend",".targetHotspot",function(b){a.pass=!0;if("touchend"==b.type){var c=b.originalEvent.changedTouches[0];a.pass=a.player.xyInElement(c.pageX,c.pageY,a.player.$elements.hotspot)}a.interacted(a.pass,b);b.stopPropagation();b.preventDefault()});this.subscribe("mouseup touchend","",function(b){a.pass=!1;a.interacted(a.pass,b)})},showDragProxy:function(a){this.player.positionDragOverlay(a);this.player.$elements.dragOverlay.show();
this.player.$elements.dragOverlay.css("opacity",1)},finish:function(){tryMe.Step.prototype.finish.call(this);this.player.resetDrag(this.pass)}});tryMe.Typed=function(){tryMe.Step.apply(this,arguments);this.currentStepValidated=this.typingTriggered=!1};tryMe.Typed.inputSelector=".targetHotspot input";
tryMe.Typed.prototype=$.extend(Object.create(tryMe.Step.prototype),{start:function(){tryMe.Step.prototype.start.call(this);this.renderInput();this.setInputType();this.player.$elements.hotspot.css({visibility:""});this.player.addFontInfoTo(this.input,this.fontInfo);this.input.removeClass("hidden");this.input[0].focus()},renderInput:function(){this.player.$elements.hotspot.html("");this.input=$('\x3cinput type\x3d"text" class\x3d"form-control hidden" id\x3d"typed-input-field"  style\x3d"padding: 0"\x3e').appendTo(this.player.$elements.hotspot)},
setInputType:function(){this.password&&this.input.attr("type","password");this.initialText&&this.input.val(this.initialText)},bindHandlers:function(){var a=this;this.subscribe("keydown",tryMe.Typed.inputSelector,function(b){~[tryMe.CONST.TAB_BUTTON,tryMe.CONST.ENTER_BUTTON].indexOf(b.keyCode)?(b.preventDefault(),a.interacted(b)):a.currentStepValidated=!1});this.subscribe("keyup",tryMe.Typed.inputSelector,function(b){b.preventDefault();a.typingTriggered=!0});this.subscribe("mouseup touchstart","",
function(b,c){c||a.player.flashTypedStepHint()});"MOUSE_MOVED"!==this.reasonTypingEnded&&"CAPTURE_STOPPED"!==this.reasonTypingEnded||this.subscribe("mousemove touchmove","",function(b){if(a.typingTriggered)return a.interacted(b),a.typingTriggered=!1})},interacted:function(a,b){var c=this.nextStepStringValidation(),d=this.nextStepReasonTypedEndedValidation(a.keyCode),e=c&&d,c=$.proxy(function(){tryMe.Step.prototype.interacted.call(this,e,a)},this);!this.hasHotspot()&&"boolean"===typeof a&&b?tryMe.Step.prototype.interacted.call(this,
a,b):e?this.doPassAnimation("MOUSE_MOVED"==this.reasonTypingEnded||"CAPTURE_ENDED"==this.reasonTypingEnded,c):c()},doPassAnimation:function(a,b){a?($(tryMe.Typed.inputSelector,this.$container).prop("disabled",!0),setTimeout(function(){$(tryMe.Typed.inputSelector,self.$container).prop("disabled",!1);b()},1E3)):b()},nextStepStringValidation:function(){var a=this.input.val().replace(/^\s+|\s+$/g,"");return this.currentStepValidated=this.regularExpression&&this.regularExpression!==this.stringTyped?this.doRegexComparison(a):
this.doTextComparison(a)},doRegexComparison:function(a){return a.match(new RegExp(this.regularExpression))?!0:!1},doTextComparison:function(a){var b=this.caseSensitive?"variant":"accent";return this.compareStringLocale("A","a","base")?this.compareStringLocale(a,this.stringTyped,b):this.compareString(a,this.stringTyped,this.caseSensitive)},nextStepReasonTypedEndedValidation:function(a){return a==tryMe.CONST.ENTER_BUTTON&&"ENTER_PRESSED"==this.reasonTypingEnded||a==tryMe.CONST.TAB_BUTTON&&"TAB_PRESSED"==
this.reasonTypingEnded||("MOUSE_MOVED"==this.reasonTypingEnded||"CAPTURE_STOPPED"==this.reasonTypingEnded)&&a!=tryMe.CONST.ENTER_BUTTON&&a!=tryMe.CONST.TAB_BUTTON||"CAPTURE_ENDED"==this.reasonTypingEnded?!0:!1},compareStringLocale:function(a,b,c){return 0===a.localeCompare(b,void 0,{sensitivity:c})},compareString:function(a,b,c){return c?stringTyped===eventStringTyped:stringTyped.toUpperCase()===eventStringTyped.toUpperCase()},hideInput:function(){this.input&&(this.input.attr("placeholder","").val(""),
this.input.hasClass("hidden")||this.input.addClass("hidden"))},hotspotResized:function(a,b){0>hotspot.width&&this.hideInput();a.css({width:b.width+"px",height:b.height+"px"})},finish:function(){tryMe.Step.prototype.finish.call(this);this.hideInput()},discardResources:function(){tryMe.Step.prototype.finish.call(this);this.player.$elements.hotspot.empty()}});tryMe.Decision=function(){tryMe.Step.apply(this,arguments);this.decisionsOptions=this.branchItems;this.panelCleared=!1};
tryMe.Decision.prototype=$.extend(Object.create(tryMe.Step.prototype),{bindHandlers:function(){this.populateDecisionFrameChoices()},showDecisionFrame:function(){$(this.player.$elements.decisionFrame).removeClass("hidden")},hideDecisionFrame:function(){$(this.player.$elements.decisionFrame).addClass("hidden")},hasHotspot:function(){return!0},populateDecisionFrameChoices:function(){var a=$("\x3cdiv class\x3d'general-container-decision-package' aria-label\x3d'"+tryMe.DEFAULTS.STRINGS.ARIA_LABEL_DECISION+
"'\x3e\x3c/div\x3e"),b=$("\x3cul class\x3d'decision-options' aria-label\x3d'"+tryMe.DEFAULTS.STRINGS.ARIA_LABEL_DECISION_OPTIONS+"'\x3e\x3c/ul\x3e"),c=$("\x3cdiv class \x3d 'general-container-decision-text-content' aria-label\x3d'"+tryMe.DEFAULTS.STRINGS.ARIA_LABEL_DECISION_INSTRUCTION+"'\x3e\x3c/div\x3e");c.html(this.instructionalText);for(var c=a.append(c),d=0;d<this.decisionsOptions.length;d++){var e="decisionOption-section-"+this.decisionsOptions[d].sectionToJumpTo,f=$('\x3cli class\x3d"decisionFrameChoice" id\x3d'+
e+'\x3e\x3ca class\x3d"btn btn-link" href\x3d"#"\x3e'+this.decisionsOptions[d].name+"\x3c/a\x3e\x3c/li\x3e");b.append(f);this.createHandlerToGoToBranch(e,this.decisionsOptions[d].sectionToJumpTo,f)}a.append(c);a.append(b);this.player.panelManager.addAndDisplayPanel(a,tryMe.CONST.PANEL_TYPES.FROM_STEP)},createHandlerToGoToBranch:function(a,b,c){var d=this;c.on("click",function(a){d.player.panelManager.closePanel();d.panelCleared=!0;var c=d.createBranchData(b,1);d.player.state.switchingSections=!0;
d.interacted(!0,a,c);d.discardResources()})},interacted:function(a,b,c){return this.interactionHandler.call(this,a,b,c)},createBranchData:function(a,b){var c={sectionToJumpTo:1,stepToReturnTo:1};a&&(c.sectionToJumpTo=a+1);b&&(c.stepToReturnTo=b);return c},finish:function(){tryMe.Step.prototype.finish.call(this)},discardResources:function(){this.panelCleared||this.player.panelManager.closePanel()}});tryMe.StopCapture=function(){tryMe.Step.apply(this,arguments)};
tryMe.StopCapture.prototype=$.extend(Object.create(tryMe.Step.prototype),{setupNoHotspot:function(){if(!this.player.getSideContainerManager(this.player).hasNextViableStepFromStepNum(this.player.state.overallStep-1))return this.interactionHandler.call(this,!0,null,null);tryMe.Step.prototype.setupNoHotspot.call(this,!0);$(this).trigger(tryMe.EVENT.STEP_FINISHED)},getRestartText:function(){return this.instructionalText}});
tryMe.Select=function(){tryMe.Step.apply(this,arguments);this.pass=!1;this.correctOption=0};
tryMe.Select.prototype=$.extend(Object.create(tryMe.Step.prototype),{start:function(){tryMe.Step.prototype.start.apply(this);this.renderSelect()},bindHandlers:function(){var a=this;this.subscribe("change",".targetHotspot select",function(b){a.pass=$(this).val()===a.correct;a.interacted(a.pass,b)})},renderSelect:function(a){a="\x3cselect\x3e";for(var b=0;b<this.options.length;b++)a+='\x3coption value\x3d"'+this.options[b]+'"'+(this.options[b]===this.initialSelection?"selected":"")+"\x3e"+this.options[b]+
"\x3c/option\x3e";this.player.$elements.hotspot.html(a+"\x3c/select\x3e");this.player.addFontInfoTo(this.player.$elements.hotspot.children().first(),this.fontInfo)},hotspotResized:function(a,b,c){a.find("select").css({transform:"scale("+c+")","transform-origin":"top left",width:1/c*b.width+"px",height:1/c*b.height+"px"})},finish:function(){this.player.$elements.hotspot.find("select").remove()}});